'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const P=require('../studio-providers');
const input={prompt:'shared identity',aspect:'16:9',size:'1280x720',count:1,seconds:4,references:[]};
async function fixture(t,handle){const server=http.createServer(handle);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});return `http://127.0.0.1:${server.address().port}`;}
function profile(protocol,baseUrl,extra={}){return{id:'connection-7',protocol,baseUrl,kind:'video',model:'veo3.1',authHeader:'Authorization',authPrefix:'Bearer',apiKey:'private-fixture',extra:{},custom:{},...extra};}
test('Runway Veo uses first/last promptImage positions and dimensions, not nonexistent lastImage',async t=>{let seen;const base=await fixture(t,(req,res)=>{let body='';req.on('data',b=>body+=b);req.on('end',()=>{seen={body:JSON.parse(body),headers:req.headers};res.end(JSON.stringify({id:'task-one',status:'PENDING'}));});});const refs=['firstFrame','lastFrame'].map((role,i)=>({role,mime:'image/png',bytes:Buffer.from([1,i,3])}));const result=await P.submit(profile('runway',base),input,refs);assert.deepEqual(seen.body.promptImage.map(v=>v.position),['first','last']);assert.equal(seen.body.ratio,'1280:720');assert.equal(seen.body.lastImage,undefined);assert.equal(result.cancelHeaders['X-Runway-Version'],'2024-11-06');});
test('Gemini defaults key header and keeps lastFrame in instances; custom flags cannot add unsupported caps',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kn-gemini-profile-')),profiles=P.createProfiles({home:dir});const visible=profiles.save({name:'Veo',kind:'video',protocol:'gemini',baseUrl:'https://generativelanguage.googleapis.com/v1beta',model:'veo-3.1-generate-preview',apiKey:'not-a-real-key'});assert.equal(visible.authHeader,'x-goog-api-key');assert.equal(visible.authPrefix,'');assert.equal(visible.inputCapabilities.lastFrame,true);});
test('usage distinguishes connections, nulls/empty strings are unknown, literal zero remains a fact',()=>{const p=profile('openai','http://127.0.0.1:9',{kind:'image'});const absent=P.normalizeUsage(p,{usage:{input_tokens:null,output_tokens:'',credits:-4}});assert.equal(absent.attempts[0].known,false);assert.deepEqual(absent.attempts[0].units,[]);const zero=P.normalizeUsage(p,{usage:{input_tokens:0,output_tokens:2}});assert.equal(zero.providerId,'connection-7');assert.equal(zero.attempts[0].known,true);assert.ok(Number.isFinite(zero.attempts[0].recordedAtMs));assert.ok(zero.attempts[0].units.some(v=>v.value===0));});
test('Gemini image generation keeps every reference and returns image bytes plus actual usage',async t=>{let seen;const base=await fixture(t,(req,res)=>{let body='';req.on('data',b=>body+=b);req.on('end',()=>{seen=JSON.parse(body);res.end(JSON.stringify({candidates:[{content:{parts:[{text:'done'},{inlineData:{mimeType:'image/png',data:'aW1hZ2U='}}]}}],usageMetadata:{promptTokenCount:15,candidatesTokenCount:7}}));});});const p=profile('gemini',base,{kind:'image',model:'gemini-image',authHeader:'x-goog-api-key',authPrefix:''});const result=await P.submit(p,input,[{mime:'image/png',bytes:Buffer.from('reference-one')},{mime:'image/png',bytes:Buffer.from('reference-two')}]);assert.equal(P.inputCapabilities(p).maxReferences,6);assert.equal(seen.contents[0].parts.length,3);assert.equal(seen.contents[0].parts[2].inlineData.data,Buffer.from('reference-two').toString('base64'));assert.equal(result.outputs[0].b64_json,'aW1hZ2U=');assert.equal(P.normalizeUsage(p,result).attempts[0].units[0].value,15);});
test('ComfyUI uploads pinned input, injects declared nodes only and tracks history/output',async t=>{const seen=[];const base=await fixture(t,(req,res)=>{const chunks=[];req.on('data',b=>chunks.push(b));req.on('end',()=>{const text=Buffer.concat(chunks).toString();seen.push({url:req.url,text});if(req.url==='/upload/image')res.end(JSON.stringify({name:'ref.png',subfolder:'input',type:'input'}));else if(req.url==='/prompt')res.end(JSON.stringify({prompt_id:'prompt-1'}));else if(req.url==='/history/prompt-1')res.end(JSON.stringify({'prompt-1':{status:{completed:true,status_str:'success'},outputs:{'9':{images:[{filename:'movie.mp4',subfolder:'',type:'output'}]}}}}));else{res.writeHead(404);res.end();}});});const p=profile('comfyui',base,{model:'My workflow',custom:{workflow:{'6':{class_type:'CLIPTextEncode',inputs:{text:'old'}},'7':{class_type:'LoadImage',inputs:{image:'old.png'}}},bindings:{prompt:{node:'6',input:'text'},firstFrame:{node:'7',input:'image'}},outputNode:'9'}});const ref={role:'firstFrame',bytes:Buffer.from('unique-reference'),mime:'image/png'};const remote=await P.submit(p,input,[ref]);assert.match(seen[0].text,/unique-reference/);const submitted=JSON.parse(seen[1].text);assert.equal(submitted.prompt['6'].inputs.text,input.prompt);assert.equal(submitted.prompt['7'].inputs.image,'input/ref.png');assert.equal(p.custom.workflow['6'].inputs.text,'old');assert.equal(remote.cancelUrl,undefined);const done=await P.poll(p,remote);assert.equal(done.done,true);assert.match(done.outputs[0].apiContent,/view\?filename=movie.mp4/);assert.equal(P.normalizeUsage(p,done).attempts[0].known,false);});
test('stream download writes bounded chunks to disk, hashes and cleans aborted partials',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kn-provider-stream-')),data=crypto.randomBytes(3*1024*1024);const base=await fixture(t,(req,res)=>{if(req.url==='/broken'){res.write(Buffer.from('partial'));setTimeout(()=>res.destroy(),20);return;}res.setHeader('content-type','video/mp4');res.end(data);});const p=profile('openai',base),file=path.join(dir,'movie.part');const output=await P.request(p,'/video',{binary:true,downloadTo:file});assert.equal(output.bytes,undefined);assert.equal(output.head.length,64);assert.equal(output.size,data.length);assert.equal(output.sha256,crypto.createHash('sha256').update(data).digest('hex'));assert.deepEqual(fs.readFileSync(file),data);const partial=path.join(dir,'failed.part');await assert.rejects(P.request(p,'/broken',{binary:true,downloadTo:partial}));assert.equal(fs.existsSync(partial),false);});
