import { expect, test } from '@playwright/test';

test.skip(!process.env.KNORVIA_UI_FIXTURE_WORKSPACE, 'Requires the isolated local gateway');
test.use({ locale: 'zh-CN' });

test('saved providers keep separate drafts, switch in a conversation, sync windows and delete', async ({ page, context }, info) => {
  test.setTimeout(100_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('knorvia-language', 'zh'));
  await page.setViewportSize({ width: 1440, height: 1060 });
  await page.goto('/workbench/settings/connection');
  const panel = page.locator('.nw-connection-settings');
  await expect(panel.getByLabel('默认模型', { exact: true })).toHaveValue('gpt-5.2');
  const originalUrl = await panel.getByLabel('服务地址', { exact: true }).inputValue();
  expect(originalUrl).toMatch(/^http:\/\/127\.0\.0\.1:/);
  await panel.getByRole('button', { name: '添加提供商', exact: true }).click();
  await panel.getByLabel('提供商名称', { exact: true }).fill('日常创作 · 备用');
  await panel.getByLabel('默认模型', { exact: true }).fill('fixture-secondary');
  await panel.getByLabel('服务地址', { exact: true }).fill(originalUrl);
  await panel.getByLabel('API 密钥', { exact: true }).fill('ui-fixture-secondary-key');
  await panel.getByRole('button', { name: '默认提供商', exact: false }).click();
  await expect(panel.getByLabel('默认模型', { exact: true })).toHaveValue('gpt-5.2');
  await expect(panel.getByLabel('API 密钥', { exact: true })).toHaveValue('');
  await panel.getByRole('button', { name: '添加提供商', exact: true }).click();
  await expect(panel.getByLabel('API 密钥', { exact: true })).toHaveValue('ui-fixture-secondary-key');
  await panel.getByRole('button', { name: '保存连接', exact: true }).click();
  await expect(panel.locator('.nw-provider-row')).toHaveCount(2);
  await expect(panel.getByLabel('API 密钥', { exact: true })).toHaveValue('');
  await expect(panel.locator('.nw-provider-row').filter({ hasText: '默认提供商' }).getByText('当前使用', { exact: true })).toBeVisible();
  await page.reload();
  await expect(panel.locator('.nw-provider-row')).toHaveCount(2);
  await panel.getByRole('button', { name: /日常创作 · 备用/ }).click();
  await expect(panel.getByLabel('API 密钥', { exact: true })).toHaveValue('');
  await page.screenshot({ path: info.outputPath('saved-providers-light.png') });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  }
  await page.setViewportSize({ width: 1440, height: 1060 });
  const other = await context.newPage();
  await other.goto('/workbench/settings/connection');
  await expect(other.locator('.nw-provider-row')).toHaveCount(2);
  await page.goto('/workbench');
  const providers = page.getByLabel('选择提供商', { exact: true });
  await expect(providers).toBeVisible();
  expect(await providers.evaluate(el => getComputedStyle(el).appearance)).toBe('base-select');
  await providers.focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Escape');
  await expect(providers).toHaveValue('default');
  await page.setViewportSize({ width: 320, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath('composer-providers-320.png') });
  await page.setViewportSize({ width: 1440, height: 1060 });
  await providers.selectOption({ label: '日常创作 · 备用' });
  await expect(page.locator('.nw-model-select > span')).toHaveText('fixture-secondary');
  await expect(other.locator('.nw-provider-row').filter({ hasText: '日常创作 · 备用' }).getByText('当前使用', { exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath('composer-provider-switch.png') });
  await page.getByLabel('任务描述', { exact: true }).fill('验证本地备用模型连接');
  await page.getByRole('button', { name: '发送任务', exact: true }).click();
  await expect(page).toHaveURL(/\/workbench\/task\//);
  await expect(page.locator('.nw-agent-message').filter({ hasText: 'scripted native fixture response' }).first()).toBeVisible({ timeout: 30_000 });
  await expect(providers).toBeEnabled();
  await providers.selectOption({ label: '默认提供商' });
  await expect(other.locator('.nw-provider-row').filter({ hasText: '默认提供商' }).getByText('当前使用', { exact: true })).toBeVisible();
  await other.getByRole('button', { name: /日常创作 · 备用/ }).click();
  await other.getByRole('button', { name: '删除提供商', exact: true }).click();
  await other.getByRole('button', { name: '确认删除', exact: true }).click();
  await expect(other.locator('.nw-provider-row')).toHaveCount(1);
  await expect(providers).toHaveCount(0);
  await other.close();
  const storage = await page.evaluate(() => JSON.stringify([Object.entries(localStorage), Object.entries(sessionStorage)]));
  expect(storage).not.toContain('ui-fixture-secondary-key');
  expect(errors).toEqual([]);
});
