import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const evidence = process.env.KNORVIA_ARTICLE_EVIDENCE;
test.skip(!evidence, 'Requires isolated article-video stack');
test('Chrome: article, Chinese voice, storyboard, preview and real MP4', async ({ page }) => {
  test.setTimeout(180000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => localStorage.setItem('knorvia-language', 'zh'));
  await page.setViewportSize({ width: 1280, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.ns-composer')).toBeVisible();
  await page.getByRole('button', { name: '文章转视频', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('标题', { exact: true }).fill('中文文章视频验收');
  await dialog.getByLabel('给谁看，希望传达什么？', { exact: true }).fill('希望轻松制作视频的个人用户');
  await dialog.getByLabel('文章或主题', { exact: true }).fill('先写清楚想说的话。再让声音带动画面。');
  await dialog.getByRole('button', { name: '创建工程', exact: true }).click();
  await dialog.getByLabel('口播稿 · 空行分段', { exact: true }).fill('先写清楚想说的话。\n\n再让声音带动画面。');
  await dialog.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '保存修改', exact: true })).toBeDisabled();
  await dialog.getByLabel('系统语音名称（留空使用默认）', { exact: true }).fill('Microsoft Huihui Desktop');
  await dialog.getByRole('button', { name: '生成完整配音', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '构建视频工程', exact: true })).toBeEnabled({ timeout: 45000 });
  await dialog.getByLabel('分镜 1 标题', { exact: true }).fill('先把话说清楚');
  await dialog.getByLabel('分镜 1 画面文字', { exact: true }).fill('一个明确的主题，是好视频的起点。');
  await dialog.getByLabel('分镜 2 标题', { exact: true }).fill('让声音带动画面');
  await dialog.getByRole('button', { name: '保存修改', exact: true }).click();
  await dialog.getByRole('button', { name: '构建视频工程', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '导出前 15 秒', exact: true })).toBeEnabled({ timeout: 15000 });
  await dialog.getByRole('button', { name: '导出前 15 秒', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '导出完整视频', exact: true })).toBeEnabled({ timeout: 90000 });
  await dialog.getByRole('button', { name: '观看预览', exact: true }).click();
  const video = dialog.locator('video'); await video.scrollIntoViewIfNeeded();
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  await video.evaluate((v: HTMLVideoElement) => new Promise<void>((resolve, reject) => { v.currentTime = 1; v.requestVideoFrameCallback(() => { v.pause(); resolve(); }); void v.play().catch(reject); }));
  fs.mkdirSync(evidence!, { recursive: true }); await page.screenshot({ path: path.join(evidence!, 'chinese-preview.png') });
  await dialog.getByRole('button', { name: '导出完整视频', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '观看成片', exact: true })).toBeVisible({ timeout: 90000 });
  await page.setViewportSize({ width: 480, height: 900 });
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: path.join(evidence!, 'narrow.png') });
  expect(errors).toEqual([]);
});
