import { toggleWorkbenchTheme } from './helpers/native-appearance';
import { expect, test, type Page } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const fixtureWorkspace = process.env.KNORVIA_UI_FIXTURE_WORKSPACE;
test.skip(!fixtureWorkspace, "Requires an explicitly isolated native gateway fixture");
test.describe.configure({ timeout: 180_000 });
test.use({ locale: "zh-CN", screenshot: "only-on-failure", trace: "retain-on-failure" });

async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.body.scrollWidth <= innerWidth && document.body.scrollHeight <= innerHeight + 1 && [...document.querySelectorAll<HTMLElement>(".nw-view, .nw-main, .nw-settings-main")].every(element => element.scrollWidth <= element.clientWidth + 1))).toBe(true);
}

test("settings and sidebars preserve actual tasks, drafts and reading context", async ({ page, context, baseURL }, testInfo) => {
  test.setTimeout(180_000);
  page.setDefaultTimeout(12_000);
  expect(["127.0.0.1", "localhost"]).toContain(new URL(baseURL!).hostname);
  expect(fixtureWorkspace!.replaceAll("\\", "/")).toContain("/isolated-home/workspace");
  const id = Date.now();
  const project = `布局验收 ${id}`;
  const title = `整理侧栏验收 ${id}`;
  let renamed = `已整理的任务 ${id}`;
  const section = `持续推进 ${id}`;
  const fileFolder = `panel-audit-${id}`;
  await fs.mkdir(path.join(fixtureWorkspace!, fileFolder), { recursive: true });
  await fs.writeFile(path.join(fixtureWorkspace!, fileFolder, "reading.md"), "# 阅读位置\n\n切换面板后保留这个文件。\n", "utf8");
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.addInitScript(() => { if (!localStorage.getItem("knorvia-language")) localStorage.setItem("knorvia-language", "zh"); });
  const shot = async (name: string) => page.screenshot({ path: testInfo.outputPath(`${name}.png`), fullPage: true });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("/workbench");
  await expect(page.locator(".nw-connection")).toHaveClass(/is-connected/);
  await page.getByRole("button", { name: "新建项目", exact: true }).click();
  await page.getByLabel("项目名称", { exact: true }).fill(project);
  await page.getByLabel("本地文件夹（可选）").first().fill(fixtureWorkspace!);
  await page.getByRole("button", { name: "创建项目", exact: true }).click();
  await expect(page.locator("dialog")).toHaveCount(0);
  await page.getByRole("textbox", { name: "任务描述", exact: true }).fill(title);
  await page.getByRole("button", { name: "发送任务", exact: true }).click();
  await expect(page.locator('.nw-task-heading [data-status="completed"]')).toBeVisible({ timeout: 30_000 });
  const taskURL = page.url();
  const sideMenu = () => page.getByRole("menu", { name: "侧栏操作" });
  const taskMenu = async (taskTitle: string) => { await page.locator(".nw-sidebar-task").filter({ has: page.getByRole("link", { name: taskTitle, exact: true }) }).getByRole("button").click(); };

  await test.step("sidebar grouping, pinning, sections, real rename, archive and fork", async () => {
    await taskMenu(title);
    await shot("sidebar-task-menu");
    await sideMenu().getByRole("menuitem", { name: "置顶任务" }).click();
    await expect(page.locator('[data-section-id="pinned"]').getByRole("link", { name: title, exact: true })).toBeVisible();
    await page.reload();
    await expect(page.locator('[data-section-id="pinned"]').getByRole("link", { name: title, exact: true })).toBeVisible();
    const other = await context.newPage();
    await other.goto("/workbench");
    await expect(other.locator('[data-section-id="pinned"]').getByRole("link", { name: title, exact: true })).toBeVisible();
    await taskMenu(title);
    await sideMenu().getByRole("menuitem", { name: "新建分区", exact: true }).click();
    await page.getByLabel("分区名称", { exact: true }).fill(section);
    await page.getByRole("button", { name: "保存分区" }).click();
    await expect(page.locator(".nw-sidebar-group").filter({ has: page.getByRole("button", { name: section, exact: true }) }).getByRole("link", { name: title, exact: true })).toBeVisible();
    await expect(other.locator('[data-section-id="pinned"]')).toHaveCount(0);
    await expect(other.locator(".nw-sidebar-group").filter({ has: other.getByRole("button", { name: section, exact: true }) }).getByRole("link", { name: title, exact: true })).toBeVisible();
    await other.close();
    const secondSection = `稍后处理 ${id}`;
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitem", { name: "新建分区", exact: true }).click();
    await page.getByLabel("分区名称", { exact: true }).fill(secondSection);
    await page.getByRole("button", { name: "保存分区" }).click();
    await page.getByRole("button", { name: `分区操作: ${secondSection}`, exact: true }).click();
    await sideMenu().getByRole("menuitem", { name: "上移分区", exact: true }).click();
    await expect(page.locator(".nw-sidebar-group[data-section-id] .nw-group-toggle").first()).toHaveText(secondSection);
    await page.getByRole("button", { name: `分区操作: ${secondSection}`, exact: true }).click();
    await sideMenu().getByRole("menuitem", { name: "重命名分区", exact: true }).click();
    await page.getByLabel("分区名称", { exact: true }).fill(`${secondSection} 已整理`);
    await page.getByRole("button", { name: "保存分区" }).click();
    await page.getByRole("button", { name: `分区操作: ${secondSection} 已整理`, exact: true }).click();
    await sideMenu().getByRole("menuitem", { name: "移除分区", exact: true }).click();
    await expect(page.locator(".nw-sidebar-group[data-section-id] .nw-group-toggle").first()).toHaveText(section);
    await taskMenu(title);
    await sideMenu().getByRole("menuitem", { name: "重命名", exact: true }).click();
    await page.getByLabel("任务名称", { exact: true }).fill(renamed);
    await page.getByRole("button", { name: "保存", exact: true }).click();
    await expect(page.locator(".nw-task-heading h1")).toHaveText(renamed);
    await expect(page).toHaveURL(taskURL);
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "在一个列表中" }).click();
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "创建时间" }).click();
    await page.reload();
    await expect(page.getByRole("button", { name: "全部对话", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await expect(sideMenu().getByRole("menuitemradio", { name: "创建时间" })).toHaveAttribute("aria-checked", "true");
    await sideMenu().getByRole("menuitemradio", { name: "按项目分组" }).click();
    await page.getByRole("button", { name: `收起项目: ${project}`, exact: true }).click();
    await page.reload();
    await expect(page.getByRole("button", { name: `展开项目: ${project}`, exact: true })).toHaveAttribute("aria-expanded", "false");
    await page.getByRole("button", { name: `展开项目: ${project}`, exact: true }).click();
    await page.keyboard.press("Control+b");
    await expect(page.locator(".nw-sidebar")).toBeHidden();
    await page.reload();
    await expect(page.locator(".nw-sidebar")).toBeHidden();
    await page.keyboard.press("Control+b");
    await expect(page.locator(".nw-sidebar")).toBeVisible();
    await taskMenu(renamed);
    await page.keyboard.press("Escape");
    await expect(page.getByRole("button", { name: `任务操作: ${renamed}`, exact: true })).toBeFocused();
    await taskMenu(renamed);
    await sideMenu().getByRole("menuitem", { name: "归档任务" }).click();
    await expect(page.locator(".nw-archived-notice")).toBeVisible();
    await page.getByRole("button", { name: "恢复任务", exact: true }).click();
    await expect(page.locator(".nw-task-composer textarea")).toBeVisible();
    await taskMenu(renamed);
    await sideMenu().getByRole("menuitem", { name: "分叉任务" }).click();
    await expect(page).not.toHaveURL(taskURL);
    await expect(page.locator(".nw-task-heading h1")).toBeVisible();
    const forkURL = page.url();
    await page.goto(taskURL);
    await taskMenu(renamed);
    await sideMenu().getByRole("menuitem", { name: "重命名", exact: true }).click();
    renamed += " · 已复核";
    await page.getByLabel("任务名称", { exact: true }).fill(renamed);
    await page.getByRole("button", { name: "保存", exact: true }).click();
    await expect(page.locator(".nw-task-heading h1")).toHaveText(renamed);
    await taskMenu(renamed);
    await sideMenu().getByRole("menuitem", { name: "默认位置", exact: true }).click();
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "在一个列表中" }).click();
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "最近更新", exact: true }).click();
    await expect(page.locator('[data-section-id="recent"] .nw-task-link').first()).toHaveAttribute("href", new URL(taskURL).pathname);
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "创建时间", exact: true }).click();
    await expect(page.locator('[data-section-id="recent"] .nw-task-link').first()).toHaveAttribute("href", new URL(forkURL).pathname);
    await taskMenu(renamed);
    await sideMenu().getByRole("menuitemradio", { name: section, exact: true }).click();
    await page.getByRole("button", { name: "整理侧栏", exact: true }).click();
    await sideMenu().getByRole("menuitemradio", { name: "按项目分组", exact: true }).click();
    await noOverflow(page);
    await shot("sidebar-sections");
  });

  await test.step("settings categories, saved theme and language, connection drafts and return", async () => {
    await page.getByRole("link", { name: "设置", exact: true }).click();
    await expect(page.locator(".nw-settings-content h1")).toHaveText("常规");
    await expect(page.locator(".nw-sidebar")).toHaveCount(0);
    await noOverflow(page); await shot("settings-general-light");
    await page.keyboard.press("Control+k");
    await expect(page.getByRole("textbox", { name: "搜索设置", exact: true })).toBeFocused();
    await page.getByRole("textbox", { name: "搜索设置", exact: true }).fill("不存在的设置名称");
    await expect(page.getByText("没有匹配的设置分类", { exact: true })).toBeVisible();
    await page.getByRole("textbox", { name: "搜索设置", exact: true }).fill("主题");
    await page.getByRole("navigation").getByRole("link", { name: "外观", exact: true }).click();
    await expect(page.locator(".nw-settings-content h1")).toHaveText("外观");
    await page.getByRole("button", { name: "深色", exact: true }).click();
    await expect(page.locator("html")).toHaveClass(/dark/);
    await page.reload();
    await expect(page.getByRole("button", { name: "深色", exact: true })).toHaveAttribute("aria-pressed", "true");
    await shot("settings-appearance-dark");
    await page.getByRole("navigation").getByRole("link", { name: "常规", exact: true }).click();
    await page.getByLabel("界面语言", { exact: true }).selectOption("en");
    await expect(page.locator(".nw-settings-content h1")).toHaveText("General");
    await page.reload();
    await expect(page.getByLabel("Interface language", { exact: true })).toHaveValue("en");
    await page.getByLabel("Interface language", { exact: true }).selectOption("zh");
    await page.getByRole("navigation").getByRole("link", { name: "模型与连接", exact: true }).click();
    const model = page.getByRole("combobox", { name: "默认模型", exact: true });
    const original = await model.inputValue();
    await expect(page.getByLabel("API 密钥", { exact: true })).toHaveValue("");
    await expect(page.getByRole("button", { name: "保存连接", exact: true })).toBeDisabled();
    await model.fill("unsaved-ui-draft");
    await page.getByRole("navigation").getByRole("link", { name: "键盘快捷键", exact: true }).click();
    await page.getByRole("textbox", { name: "搜索快捷键", exact: true }).fill("右侧");
    await expect(page.locator(".nw-preference-row:visible")).toHaveCount(1);
    await expect(page.locator(".nw-shortcut-keys")).toHaveText("CtrlAltB");
    await page.getByRole("navigation").getByRole("link", { name: "模型与连接", exact: true }).click();
    await expect(model).toHaveValue("unsaved-ui-draft");
    await page.getByRole("button", { name: "重新读取", exact: true }).click();
    await expect(model).toHaveValue(original);
    await expect(page.getByRole("button", { name: "保存连接", exact: true })).toBeDisabled();
    await noOverflow(page); await shot("settings-connection-dark");
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 }); await noOverflow(page); await shot(`settings-connection-${width}`);
      await page.getByRole("button", { name: "展开设置导航", exact: true }).click();
      await expect(page.getByRole("complementary", { name: "设置导航" })).toBeVisible();
      await noOverflow(page); await shot(`settings-navigation-${width}`);
      await page.getByRole("navigation").getByRole("link", { name: "常规", exact: true }).click();
      await expect(page.getByRole("complementary", { name: "设置导航" })).toBeHidden();
      await noOverflow(page);
      await page.getByRole("button", { name: "展开设置导航", exact: true }).click();
      await page.getByRole("navigation").getByRole("link", { name: "模型与连接", exact: true }).click();
    }
    await page.setViewportSize({ width: 1600, height: 1000 });
    await page.goto(taskURL);
    await expect(page.locator(".nw-task-heading h1")).toHaveText(renamed);
    await page.getByRole("link", { name: "设置", exact: true }).click();
    await page.getByRole("link", { name: "返回应用", exact: true }).click();
    await expect(page).toHaveURL(taskURL);
    await expect(page.locator(".nw-task-heading h1")).toHaveText(renamed);
  });

  await test.step("right work panel keeps files and drafts, tabs, width, output and narrow keyboard flow", async () => {
    const composer = page.locator(".nw-task-composer textarea").first();
    await composer.fill("切换侧栏时保留这段草稿");
    await page.keyboard.press("Control+Alt+b");
    const panel = page.getByRole("complementary", { name: "右侧工作面板", exact: true });
    await expect(panel).toBeVisible();
    await panel.locator(".nw-panel-launch-actions").getByRole("button", { name: /^文件/ }).click();
    await panel.getByRole("button", { name: fileFolder, exact: true }).click();
    await panel.getByRole("button", { name: "reading.md", exact: true }).click();
    await expect(panel.locator(".nw-panel-file:not([hidden]) .nw-markdown")).toContainText("切换面板后保留这个文件");
    await panel.getByRole("button", { name: "打开工作区入口", exact: true }).click();
    await panel.getByRole("button", { name: "任务活动", exact: true }).click();
    await panel.getByRole("button", { name: "打开工作区入口", exact: true }).click();
    await panel.getByRole("button", { name: "项目改动", exact: true }).click();
    await expect(panel.getByText("这个文件夹未使用 Git", { exact: true })).toBeVisible();
    await panel.getByRole("tab", { name: "reading.md", exact: true }).click();
    await expect(panel.locator(".nw-panel-file:not([hidden]) .nw-markdown")).toContainText("切换面板后保留这个文件");
    const resize = panel.getByRole("separator", { name: "调整右侧面板宽度" });
    await resize.focus(); await resize.press("ArrowLeft");
    await expect(resize).toHaveAttribute("aria-valuenow", "512");
    await expect.poll(() => page.evaluate(() => localStorage.getItem("knorvia-native-panel-width"))).toBe("512");
    const handle = (await resize.boundingBox())!;
    await page.mouse.move(handle.x + handle.width / 2, handle.y + 90);
    await page.mouse.down(); await page.mouse.move(handle.x - 40, handle.y + 90, { steps: 4 }); await page.mouse.up();
    expect(Number(await resize.getAttribute("aria-valuenow"))).toBeGreaterThan(535);
    await resize.dblclick(); await resize.focus(); await resize.press("ArrowLeft");
    await expect(resize).toHaveAttribute("aria-valuenow", "512");
    await noOverflow(page); await shot("right-files-dark");
    await panel.getByRole("button", { name: "关闭工作面板", exact: true }).click();
    await expect(composer).toHaveValue("切换侧栏时保留这段草稿");
    await page.keyboard.press("Control+Alt+b");
    await expect(panel.locator(".nw-panel-file:not([hidden]) .nw-markdown")).toContainText("切换面板后保留这个文件");
    await page.keyboard.press("Escape");
    await expect(panel).toBeHidden();
    await page.getByRole("button", { name: "保存为成果", exact: true }).click();
    await expect(page.locator(".nw-toast")).toContainText("成果");
    await page.getByRole("button", { name: "资料与成果", exact: true }).click();
    const resources = page.getByRole("complementary", { name: "资料与成果", exact: true });
    await resources.getByRole("button", { name: renamed, exact: true }).click();
    await expect(panel.locator(".nw-panel-artifact .nw-markdown")).toContainText("scripted native fixture response");
    await panel.getByRole("button", { name: "扩大面板", exact: true }).click();
    await noOverflow(page); await shot("right-output-expanded");
    await panel.getByRole("button", { name: "还原面板宽度", exact: true }).click();
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 }); await noOverflow(page); await shot(`right-output-${width}`);
      await panel.getByRole("tab", { name: "reading.md", exact: true }).click();
      await expect(panel.locator(".nw-panel-file:not([hidden]) .nw-markdown")).toContainText("切换面板后保留这个文件");
      await panel.getByRole("button", { name: "加入任务", exact: true }).click();
      await panel.getByRole("button", { name: "关闭工作面板", exact: true }).focus();
      await page.keyboard.press("Tab");
      expect(await panel.evaluate(element => element.contains(document.activeElement))).toBe(true);
      await page.keyboard.press("Escape"); await expect(panel).toBeHidden();
      await expect(composer).toHaveValue("切换侧栏时保留这段草稿");
      await noOverflow(page);
      await page.getByRole("button", { name: "展开侧栏", exact: true }).click();
      await noOverflow(page); await shot(`left-sidebar-${width}`);
      await page.keyboard.press("Escape");
      await page.keyboard.press("Control+Alt+b");
    }
    await page.keyboard.press("Escape");
    await page.setViewportSize({ width: 1600, height: 1000 });
    await toggleWorkbenchTheme(page);
    await page.keyboard.press("Control+Alt+b");
    await noOverflow(page); await shot("right-files-light");
    await page.keyboard.press("Escape");
    await page.reload();
    await expect(composer).toHaveValue("切换侧栏时保留这段草稿");
    await page.keyboard.press("Control+Alt+b");
    await expect(panel.getByRole("separator", { name: "调整右侧面板宽度" })).toHaveAttribute("aria-valuenow", "512");
  });
  expect(errors).toEqual([]);
});
