import { expect, test, type Page } from '@playwright/test';
import http from 'node:http';
import path from 'node:path';
import fs from 'node:fs';
import type { EditProject, EditRender } from '../lib/studio-edit';
const origin = process.env.KNORVIA_NIGHT_IMAGE_ORIGIN;
test.skip(!origin || !process.env.KNORVIA_UI_FIXTURE_WORKSPACE, 'Requires an isolated local studio gateway');
test.use({ locale: 'zh-CN' });
async function rpc<T>(page: Page, method: string, params: Record<string, unknown> = {}): Promise<T> {
  return page.evaluate(async ({ method, params }) => {
    const socket = (window as unknown as { __editSockets: WebSocket[] }).__editSockets.find(s => s.readyState === 1 && s.protocol.includes('knorvia'));
    if (!socket) throw Error('No native fixture socket');
    const id = crypto.randomUUID();
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => { socket.removeEventListener('message', receive); reject(Error(method + ' timeout')); }, 30000);
      function receive(event: MessageEvent) { const r = JSON.parse(String(event.data)); if (r.id !== id) return; clearTimeout(timer); socket!.removeEventListener('message', receive); if (r.error) reject(Error(r.error.message)); else resolve(r.result); }
      socket.addEventListener('message', receive); socket.send(JSON.stringify({ jsonrpc: '2.0', id, method, params }));
    });
  }, { method, params }) as Promise<T>;
}
test('Chrome: completed shots become an editable film and workflow files are imported visually', async ({ page }, info) => {
  test.setTimeout(180000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => {
    localStorage.setItem('knorvia-language', 'zh');
    const Native = window.WebSocket; const sockets: WebSocket[] = [];
    (window as unknown as { __editSockets: WebSocket[] }).__editSockets = sockets;
    window.WebSocket = class extends Native { constructor(url: string | URL, protocols?: string | string[]) { super(url, protocols); sockets.push(this); } };
  });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  const profile = await rpc<{ id: string }>(page, 'studio/model/save', { name: '本地视频验收', kind: 'video', protocol: 'fal', model: 'fal-ai/fixture/video', baseUrl: origin, custom: { firstFrameField: 'image_url', lastFrameField: 'last_image_url' } });
  const title = `成片验收-${Date.now()}`;
  const sequence = await rpc<{ id: string }>(page, 'studio/sequence/create', { title, defaults: { profileId: profile.id, seconds: 1 }, shots: [{ prompt: '第一段', continuity: 'none' }, { prompt: '第二段', continuity: 'none' }], start: true, idempotencyKey: crypto.randomUUID() });
  await expect.poll(async () => { await fetch(`${origin}/__night/release-video`); return (await rpc<{ state: string }>(page, 'studio/sequence/read', { id: sequence.id })).state; }, { timeout: 60000 }).toBe('completed');
  await page.reload(); await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  await page.locator('.ns-sequence-toggle').click();
  await page.getByRole('button', { name: title, exact: false }).click();
  await page.getByRole('button', { name: '剪辑成片', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('.ns-timeline-track > li')).toHaveCount(2);
  await dialog.getByLabel('后移镜头', { exact: true }).first().click();
  await expect(dialog.locator('.ns-timeline-shot strong').first()).toHaveText('第二段');
  await dialog.getByLabel('开始（秒）', { exact: true }).fill('0.067');
  await dialog.getByLabel('结束（秒）', { exact: true }).fill('0.333');
  await dialog.getByLabel('成片画幅').selectOption('9:16');
  await dialog.getByRole('button', { name: '保存剪辑', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '保存剪辑', exact: true })).toBeDisabled();
  await dialog.getByText('字幕', { exact: true }).click();
  await dialog.getByRole('button', { name: '添加字幕', exact: true }).click();
  await dialog.getByLabel('字幕内容', { exact: true }).fill('晨光中的镜头');
  await dialog.getByLabel('字幕结束（秒）').fill('0.2');
  await dialog.getByRole('button', { name: '导出 MP4', exact: true }).click();
  await expect(dialog.getByText('成片已存入资料库', { exact: false })).toBeVisible({ timeout: 60000 });
  await dialog.getByRole('button', { name: '查看成片', exact: true }).click();
  await expect.poll(() => dialog.locator('video').evaluate((v: HTMLVideoElement) => v.videoWidth)).toBe(720);
  await expect.poll(() => dialog.locator('video').evaluate((v: HTMLVideoElement) => Array.from(v.textTracks).some(track => track.mode === 'showing' && track.cues?.length === 1))).toBe(true);
  await dialog.locator('video').evaluate((v: HTMLVideoElement) => new Promise<void>((resolve, reject) => { v.requestVideoFrameCallback(() => { v.pause(); resolve(); }); void v.play().catch(reject); }));
  await expect.poll(() => dialog.locator('video').evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  const geometry = await dialog.locator('video').evaluate((v: HTMLVideoElement) => ({ video: v.getBoundingClientRect().toJSON(), parent: v.parentElement!.getBoundingClientRect().toJSON(), style: { visibility: getComputedStyle(v).visibility, opacity: getComputedStyle(v).opacity, objectFit: getComputedStyle(v).objectFit }, time: v.currentTime, state: v.readyState }));
  await info.attach('video-layout', { body: JSON.stringify(geometry), contentType: 'application/json' });
  expect(geometry.video.height).toBeLessThanOrEqual(geometry.parent.height + 1);
  const evidence = path.resolve(process.env.KNORVIA_VIDEO_SCREENSHOTS || '../docs/engineering/video-workflows/2026-09-08/acceptance/screenshots'); fs.mkdirSync(evidence, { recursive: true });
  await page.screenshot({ path: path.join(evidence, 'timeline-wide.png') });
  await page.setViewportSize({ width: 430, height: 850 });
  await expect.poll(() => dialog.evaluate(d => d.scrollWidth <= d.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: path.join(evidence, 'timeline-narrow.png') });
  await dialog.getByLabel('关闭对话框').click(); await expect(dialog).toHaveCount(0);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: '剪辑成片', exact: true }).click();
  await expect(dialog.locator('.ns-timeline-shot strong').first()).toHaveText('第二段');
  await expect(dialog.getByLabel('成片画幅')).toHaveValue('9:16');
  await dialog.getByText('局部重做', { exact: true }).click();
  await dialog.getByRole('combobox', { name: '重做模型', exact: true }).selectOption(profile.id);
  await dialog.getByLabel('重做开始（秒）').fill('0.1');
  await dialog.getByLabel('重做结束（秒）').fill('0.2');
  await dialog.getByLabel('修改要求', { exact: true }).fill('本地验收：只重做中间片段');
  await dialog.getByRole('button', { name: '生成候选片段', exact: true }).click();
  await expect.poll(async () => { await fetch(`${origin}/__night/release-video`); return dialog.getByText('候选片段已就绪', { exact: true }).isVisible(); }, { timeout: 60000 }).toBe(true);
  await dialog.getByRole('button', { name: '预览候选', exact: true }).click();
  await expect.poll(() => dialog.getByLabel('重做候选预览').evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  await dialog.getByRole('button', { name: '应用候选', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '撤销这次替换', exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(evidence, 'retake-candidate.png') });
  await dialog.getByRole('button', { name: '撤销这次替换', exact: true }).click();
  await expect(dialog.locator('.ns-timeline-shot strong').first()).toHaveText('第二段');
  await dialog.getByLabel('关闭对话框').click();
  const calls: string[] = [];
  const server = http.createServer((req, res) => { calls.push(`${req.method} ${req.url}`); res.setHeader('content-type', 'application/json'); res.end(JSON.stringify(req.url?.endsWith('/Text') ? { Text: { input: { required: { text: ['STRING'] } } } } : { Save: { input: { required: { text: ['STRING'] } } } })); });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  try {
    await page.getByRole('button', { name: '模型连接', exact: true }).click();
    await dialog.getByRole('button', { name: '添加', exact: true }).click();
    await dialog.getByLabel('连接名称', { exact: true }).fill(title + '-工作流导入');
    await dialog.getByLabel('接口协议').selectOption('comfyui');
    await dialog.getByLabel('接口地址', { exact: true }).fill(`http://127.0.0.1:${(server.address() as { port: number }).port}`);
    await dialog.getByLabel('模型名称或端点', { exact: true }).fill('local-workflow');
    const upload = dialog.locator('.ns-workflow input[type=file]');
    await upload.setInputFiles({ name: 'canvas.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ nodes: [], links: [] })) });
    await expect(dialog.getByRole('alert')).toContainText('画布文件');
    await upload.setInputFiles({ name: 'api.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ '6': { class_type: 'Text', inputs: { text: '山水' } }, '9': { class_type: 'Save', inputs: { text: ['6', 0] } } })) });
    await expect(dialog.locator('.ns-workflow')).toContainText('2 个节点');
    await dialog.locator('.ns-workflow').getByLabel('提示词', { exact: true }).selectOption(JSON.stringify(['6', 'text']));
    await dialog.locator('.ns-workflow').getByLabel('输出节点', { exact: true }).selectOption('9');
    await page.screenshot({ path: path.join(evidence, 'workflow-import.png') });
    await dialog.getByRole('button', { name: '保存连接', exact: true }).click(); await expect(dialog).toHaveCount(0);
    await page.getByRole('button', { name: '模型连接', exact: true }).click();
    const models = await rpc<{ profiles: { id: string; name: string }[] }>(page, 'studio/models');
    await dialog.getByLabel('已保存的连接').selectOption(models.profiles.find(p => p.name === title + '-工作流导入')!.id);
    await dialog.getByRole('button', { name: '测试已保存配置', exact: true }).click();
    await expect(dialog.getByRole('status')).toContainText('已保存的接口连接正常');
    expect(calls).toEqual(['GET /object_info/Text', 'GET /object_info/Save']);
    await dialog.getByLabel('关闭对话框').click();
    const project = await rpc<EditProject>(page, 'studio/edit/create', { sequenceId: sequence.id });
    const render = await rpc<EditRender>(page, 'studio/edit/render/read', { id: project.lastRenderId });
    await info.attach('durable-edit', { body: JSON.stringify({ project, render, errors }), contentType: 'application/json' });
    expect(errors).toEqual([]);
    fs.writeFileSync(path.join(evidence, '../chrome-result.json'), JSON.stringify({ at: new Date().toISOString(), project, render, errors, calls, passed: true }, null, 2));
  } finally { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
