import { toggleWorkbenchTheme } from './helpers/native-appearance';
import { expect, test } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';

const workspace = process.env.KNORVIA_UI_FIXTURE_WORKSPACE;
test.skip(!workspace, 'Requires isolated native fixture');
test.use({ locale: 'zh-CN', screenshot: 'only-on-failure' });
const alive = (pid: number) => { try { process.kill(pid, 0); return true; } catch { return false; } };

test('real terminal preserves the task, runs commands, restores sessions and ends its process tree', async ({ page, baseURL }, info) => {
  test.setTimeout(100_000); page.setDefaultTimeout(10_000);
  expect(workspace!.replaceAll('\\', '/')).toContain('/isolated-home/workspace');
  expect(new URL(baseURL!).hostname).toBe('127.0.0.1');
  const id = Date.now(), prefix = `terminal-${id}`, title = `终端接入验收 ${id}`;
  const file = (name: string) => path.join(workspace!, `${prefix}-${name}`);
  await fs.writeFile(file('child.js'), `require('fs').writeFileSync(${JSON.stringify(file('child.pid'))}, String(process.pid));setInterval(()=>{},1000);`);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const shot = (name: string) => page.screenshot({ path: info.outputPath(`${name}.png`), fullPage: true });
  const noOverflow = async () => expect(await page.evaluate(() => document.body.scrollWidth <= innerWidth && document.body.scrollHeight <= innerHeight + 1)).toBe(true);
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('knorvia-language', 'zh'); });
  await page.setViewportSize({ width: 1600, height: 1000 }); await page.goto('/workbench');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  await page.getByRole('button', { name: '新建项目', exact: true }).click();
  await page.getByLabel('项目名称', { exact: true }).fill(title);
  await page.getByLabel('本地文件夹（可选）').first().fill(workspace!);
  await page.getByRole('button', { name: '创建项目', exact: true }).click();
  await expect(page.locator('dialog')).toHaveCount(0);
  await page.getByRole('textbox', { name: '任务描述', exact: true }).fill(title);
  await page.getByRole('button', { name: '发送任务', exact: true }).click();
  await expect(page.locator('.nw-task-heading [data-status="completed"]')).toBeVisible({ timeout: 25_000 });
  const taskURL = page.url(), composer = page.locator('.nw-task-composer textarea').first();
  await composer.fill('接入终端，主对话草稿保留');
  await page.getByRole('button', { name: '右侧工作面板', exact: true }).click();
  const panel = page.getByRole('complementary', { name: '右侧工作面板', exact: true });
  await expect(panel.locator('.nw-panel-launch-actions button')).toHaveCount(4);
  await shot('terminal-launcher');
  await panel.locator('.nw-panel-launch-actions').getByRole('button', { name: /^终端/ }).click();
  const terminal = () => panel.locator('.nw-panel-terminal:not([hidden]) .nw-terminal');
  const run = async (command: string) => {
    await expect(terminal()).toHaveAttribute('data-status', 'running');
    await terminal().locator('textarea').focus();
    await terminal().locator('textarea').evaluate((element, text) => {
      const clipboard = new DataTransfer(); clipboard.setData('text/plain', text);
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: clipboard, bubbles: true, cancelable: true }));
    }, command);
    await page.keyboard.press('Enter');
  };
  const read = async (name: string) => { try { return await fs.readFile(file(name), 'utf8'); } catch { return ''; } };
  await run(`$knorviaNote='中文会话保留'; [IO.File]::WriteAllText('${prefix}-pid.txt',[string]$PID); [IO.File]::WriteAllText('${prefix}-cwd.txt',$pwd.Path); Write-Host 'Knorvia terminal ready' -ForegroundColor Green`);
  await expect.poll(() => read('cwd.txt')).toBe(workspace);
  await terminal().locator('textarea').focus();
  await page.keyboard.type(`Write-Output keyboard-ok > '${prefix}-keyboard.txt'`); await page.keyboard.press('Enter');
  await expect.poll(async () => { try { return await fs.readFile(file('keyboard.txt'), 'utf16le'); } catch { return ''; } }).toContain('keyboard-ok');
  const pid = Number(await read('pid.txt')); expect(pid).toBeGreaterThan(0);
  const sessionId = await terminal().getAttribute('data-session-id');
  await expect(composer).toHaveValue('接入终端，主对话草稿保留'); await expect(page).toHaveURL(taskURL);
  await noOverflow(); await shot('terminal-running');
  await page.keyboard.press('Control+b'); await expect(page.locator('.nw-sidebar')).toBeVisible();
  await page.keyboard.press('Control+k'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.keyboard.press('Escape'); await expect(panel).toBeVisible();
  await page.keyboard.press('Tab'); await expect(terminal().locator('textarea')).toBeFocused();
  await page.keyboard.press('Control+c');
  await page.keyboard.press('Control+Shift+m'); await expect(panel.getByRole('tab', { selected: true })).toBeFocused();
  await panel.getByRole('button', { name: '关闭工作面板', exact: true }).click();
  await page.keyboard.press('Control+Alt+b');
  await expect(terminal()).toHaveAttribute('data-session-id', sessionId!);
  await run(`[IO.File]::WriteAllText('${prefix}-preserved.txt',$knorviaNote)`);
  await expect.poll(() => read('preserved.txt')).toBe('中文会话保留');
  await panel.getByRole('button', { name: '打开工作区入口', exact: true }).click();
  await panel.locator('.nw-panel-launch-actions').getByRole('button', { name: /^文件/ }).click();
  await panel.getByRole('tab', { name: '终端 1', exact: true }).click();
  await expect(terminal()).toHaveAttribute('data-session-id', sessionId!);
  await panel.getByRole('separator', { name: '调整右侧面板宽度' }).focus(); await page.keyboard.press('End');
  await noOverflow(); await shot('terminal-expanded-width');
  await run(`& 'D:\\node-v26.3.0-win-x64\\node.exe' '${prefix}-child.js'`);
  await expect.poll(() => read('child.pid')).toMatch(/^\d+$/);
  const child = Number(await read('child.pid')); expect(alive(child)).toBe(true);
  await terminal().locator('textarea').focus(); await page.keyboard.press('Control+c');
  await expect.poll(() => alive(child)).toBe(false);
  await run(`[IO.File]::WriteAllText('${prefix}-interrupted.txt','resumed')`);
  await expect.poll(() => read('interrupted.txt')).toBe('resumed');
  // Renderer reload must reattach to the same shell, preserving variables and PID.
  await page.reload(); await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  await expect(panel).toBeVisible();
  await panel.getByRole('tab', { name: '终端 1', exact: true }).click();
  await run(`[IO.File]::WriteAllText('${prefix}-restored.txt',"$PID $knorviaNote")`);
  await expect.poll(() => read('restored.txt')).toBe(`${pid} 中文会话保留`);
  await terminal().locator('textarea').focus(); await page.keyboard.press('Control+Backquote');
  await expect(panel.getByRole('tab', { name: /^终端/ })).toHaveCount(2);
  await run(`Write-Host 'Independent terminal'`);
  await run('exit 7'); await expect(terminal()).toHaveAttribute('data-status', 'exited');
  await expect(terminal()).toContainText('进程已退出，退出码 7');
  const exitedSession = await terminal().getAttribute('data-session-id');
  await page.reload(); await expect(panel).toBeVisible();
  await expect(terminal()).toHaveAttribute('data-session-id', exitedSession!);
  await expect(terminal()).toHaveAttribute('data-status', 'exited');
  await shot('terminal-exit');
  await terminal().getByRole('button', { name: '结束并关闭终端', exact: true }).click();
  await panel.getByRole('tab', { name: '终端 1', exact: true }).click();
  await panel.getByRole('button', { name: '关闭工作面板', exact: true }).click();
  await toggleWorkbenchTheme(page); await page.keyboard.press('Control+Alt+b');
  await noOverflow(); await shot('terminal-dark');
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 }); await noOverflow();
    await expect.poll(() => terminal().locator('.xterm-screen').evaluate(element => element.getBoundingClientRect().right <= innerWidth - 6)).toBe(true);
    await shot(`terminal-${width}`);
  }
  await page.setViewportSize({ width: 1600, height: 1000 });
  await fs.unlink(file('child.pid'));
  await run(`& 'D:\\node-v26.3.0-win-x64\\node.exe' '${prefix}-child.js'`);
  await expect.poll(() => read('child.pid')).toMatch(/^\d+$/);
  const child2 = Number(await read('child.pid'));
  await terminal().getByRole('button', { name: '结束并关闭终端', exact: true }).click();
  await expect(panel.getByRole('tab', { name: /^终端/ })).toHaveCount(0);
  await expect.poll(() => alive(pid) || alive(child2)).toBe(false);
  await expect(panel.getByRole('tab', { name: '文件', exact: true })).toHaveAttribute('aria-selected', 'true');
  await panel.getByRole('button', { name: '关闭标签: 文件', exact: true }).click();
  await expect(panel.locator('.nw-panel-launcher')).toBeVisible();
  expect(errors).toEqual([]);
});
