import { expect, test } from '@playwright/test';

const workspace = process.env.KNORVIA_UI_FIXTURE_WORKSPACE;
const imageOrigin = process.env.KNORVIA_NIGHT_IMAGE_ORIGIN;
test.skip(!workspace || !imageOrigin, 'Requires the night studio stack (gateway fixture and image fixture)');
test.use({ locale: 'zh-CN', screenshot: 'only-on-failure' });

test('creation studio connects a local model, generates an image, and the outputs page previews the durable artifact', async ({ page }, info) => {
  test.setTimeout(180_000);
  expect(workspace!.replaceAll('\\', '/')).toContain('/isolated-home/workspace');
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('knorvia-language', 'zh'); });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);

  // No template wall: the create section hosts only the composer, the real
  // connection dialog and the personal history — never preset sample works.
  const composer = page.locator('.ns-composer');
  await expect(composer).toBeVisible();

  // Connect a user-defined model pointing at the loopback image fixture.
  // The journey is idempotent: a connection persisted by an earlier leg is
  // re-pointed at the current fixture port instead of duplicated.
  await page.getByRole('button', { name: '模型连接', exact: true }).click();
  const dialog = page.getByRole('dialog');
  const savedSelect = dialog.getByLabel('已保存的连接', { exact: true });
  if (await savedSelect.locator('option', { hasText: '本机验收图片模型' }).count()) {
    await savedSelect.selectOption({ label: '本机验收图片模型' });
  } else {
    await dialog.getByLabel('连接名称', { exact: true }).fill('本机验收图片模型');
  }
  await dialog.getByLabel('接口地址', { exact: true }).fill(`${imageOrigin}/v1`);
  await dialog.getByLabel('模型名称或端点', { exact: true }).fill('fixture-model');
  // No API key: an optional local service without authentication.
  await dialog.getByLabel('允许 Agent 使用此模型创作', { exact: true }).check();
  await dialog.getByRole('button', { name: '保存连接', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(composer).toContainText('本机验收图片模型');

  // Submit a real creation through the composer.
  await page.getByLabel('创作描述', { exact: true }).fill('一顶红色贝雷帽的静物写生');
  await page.getByRole('button', { name: '开始创作', exact: true }).click();
  await expect(page.getByRole('status').last()).toContainText('已加入创作队列');

  // The durable job reaches its terminal published phase.
  const job = page.locator('.ns-job').first();
  await expect(job).toHaveAttribute('data-phase', 'completed', { timeout: 60_000 });
  await expect(job).toContainText('已完成');
  await expect(job).not.toContainText('Invalid Date');
  await expect(job.locator('.ns-job-copy > span')).toContainText(/\d+月\d+日/);
  await expect(job.locator('.ns-job-open')).toHaveCSS('display', 'block');
  const cardLayout = await job.evaluate(el => {
    const media = el.querySelector('.ns-media')!.getBoundingClientRect();
    const copy = el.querySelector('.ns-job-copy')!.getBoundingClientRect();
    return { mediaBottom: media.bottom, copyTop: copy.top, mediaWidth: media.width, copyWidth: copy.width };
  });
  expect(cardLayout.copyTop).toBeGreaterThanOrEqual(cardLayout.mediaBottom - 1);
  expect(Math.abs(cardLayout.mediaWidth - cardLayout.copyWidth)).toBeLessThan(1);

  // The preview streams the real generated bytes from the studio worker.
  await job.getByRole('button').first().click();
  const previewDialog = page.getByRole('dialog');
  const media = previewDialog.locator('.ns-media img');
  await expect(media).toBeVisible({ timeout: 30_000 });
  const src = await media.getAttribute('src');
  expect(src).toContain('blob:');
  await page.screenshot({ path: info.outputPath('studio-preview.png'), fullPage: true });

  // Save to the personal library from the creation studio.
  await previewDialog.getByRole('button', { name: '存入资料库', exact: true }).click();
  await expect(page.locator('.nw-toast', { hasText: '已保存到个人资料库' })).toBeVisible({ timeout: 15_000 });
  await previewDialog.getByRole('button', { name: '继续创作', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByLabel('创作描述', { exact: true })).toBeFocused();
  await expect(page.getByLabel('创作描述', { exact: true })).toHaveValue('一顶红色贝雷帽的静物写生');

  // The outputs page consumes the same durable artifact manifest.
  await page.getByRole('link', { name: '成果', exact: true }).click();
  await page.waitForURL('**/workbench/artifacts', { timeout: 30_000 });
  const row = page.locator('.nw-output-row', { hasText: '一顶红色贝雷帽的静物写生' }).first();
  await expect(row).toContainText('生成的图片/视频');
  await row.click();
  const reader = page.locator('.nw-output-reader');
  await expect(reader.locator('.nw-media-frame img')).toBeVisible({ timeout: 30_000 });
  await expect(reader.locator('.nw-media-meta').first()).toContainText('sha256');
  await expect(reader.getByRole('button', { name: '下载', exact: true })).toBeEnabled();
  await page.screenshot({ path: info.outputPath('outputs-media-preview.png'), fullPage: true });

  // Library received the saved copy.
  await page.getByRole('link', { name: '资料库', exact: true }).click();
  await expect(page).toHaveURL(/\/workbench\/library$/);
  await expect(page.locator('.nl-folder-tree').getByRole('button', { name: /^创作$/, exact: true })).toBeVisible({ timeout: 30_000 });
});

test('video creation can be cancelled with honest remote state, then completes and previews a decodable video', async ({ page }, info) => {
  test.setTimeout(240_000);
  expect(workspace!.replaceAll('\\', '/')).toContain('/isolated-home/workspace');
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('knorvia-language', 'zh'); });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);

  // Switch to video creation and connect a fal-style queue fixture.
  await page.locator('.ns-kind').getByRole('button', { name: '视频', exact: true }).click();
  await page.getByRole('button', { name: '模型连接', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('连接名称', { exact: true }).fill('本机验收视频模型');
  await dialog.getByLabel('接口协议').selectOption('fal');
  await dialog.getByLabel('接口地址', { exact: true }).fill(imageOrigin!);
  await dialog.getByLabel('模型名称或端点', { exact: true }).fill('fal-ai/fixture/video');
  await dialog.getByLabel('允许 Agent 使用此模型创作', { exact: true }).check();
  await dialog.getByRole('button', { name: '保存连接', exact: true }).click();
  await expect(dialog).toHaveCount(0);

  const cancelPrompt = `取消验收 ${Date.now()}`;
  await page.getByLabel('创作描述', { exact: true }).fill(cancelPrompt);
  await page.getByRole('button', { name: '开始创作', exact: true }).click();
  const cancelJob = page.locator('.ns-job', { hasText: cancelPrompt });
  await expect(cancelJob).toBeVisible({ timeout: 30_000 });
  await cancelJob.getByRole('button', { name: '停止生成', exact: true }).click();
  await expect(cancelJob).toHaveAttribute('data-phase', 'stopped', { timeout: 60_000 });
  await expect(cancelJob).toContainText('已停止');
  // Cancellation is honest: local tracking stopped, the provider may continue.
  await cancelJob.getByRole('button').first().click();
  const cancelDialog = page.getByRole('dialog');
  await expect(cancelDialog).toContainText('服务商可能仍在生成并计费');
  await cancelDialog.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);

  // A fresh submission completes once the fixture queue is released.
  const donePrompt = `完成验收 ${Date.now()}`;
  await page.getByLabel('创作描述', { exact: true }).fill(donePrompt);
  await page.getByRole('button', { name: '开始创作', exact: true }).click();
  await expect(page.locator('.nw-toast', { hasText: '已加入创作队列' })).toBeVisible({ timeout: 15_000 });
  // The worker polls on its own cadence; keep releasing until the job completes.
  const doneJob = page.locator('.ns-job', { hasText: donePrompt });
  await expect.poll(async () => {
    await fetch(`${imageOrigin}/__night/release-video`).catch(() => {});
    await doneJob.getAttribute('data-phase').catch(() => null);
    return doneJob.getAttribute('data-phase').catch(() => null);
  }, { timeout: 150_000 }).toBe('completed');
  await doneJob.getByRole('button').first().click();
  const previewDialog = page.getByRole('dialog');
  const video = previewDialog.locator('.ns-media video');
  await expect(video).toBeVisible({ timeout: 30_000 });
  const duration = await video.evaluate((element: HTMLVideoElement) => element.duration);
  expect(duration).toBeGreaterThan(0);
  await page.screenshot({ path: info.outputPath('studio-video-preview.png'), fullPage: true });
  // The downloaded bytes must be identical to the provider fixture bytes.
  const previewDownload = page.waitForEvent('download');
  await previewDialog.locator('.ns-media-download').click();
  const crypto = await import('node:crypto');
  const fsModule = await import('node:fs');
  const downloaded = await (await previewDownload).path();
  const downloadedSha = crypto.createHash('sha256').update(fsModule.readFileSync(downloaded!)).digest('hex');
  const sourceResponse = await fetch(`${imageOrigin}/fixture.mp4`);
  const sourceSha = crypto.createHash('sha256').update(Buffer.from(await sourceResponse.arrayBuffer())).digest('hex');
  expect(downloadedSha).toBe(sourceSha);
});

test('removing every model connection keeps history readable and the composer offers a real reconnect path', async ({ page }) => {
  test.setTimeout(120_000);
  expect(workspace!.replaceAll('\\', '/')).toContain('/isolated-home/workspace');
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('knorvia-language', 'zh'); });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  // Delete every saved connection inside one dialog session.
  await page.getByRole('button', { name: '模型连接', exact: true }).click();
  const dialog = page.getByRole('dialog');
  for (let round = 0; round < 6; round += 1) {
    const savedSelect = dialog.getByLabel('已保存的连接');
    const options = await savedSelect.locator('option').count();
    if (options <= 1) break;
    const label = await savedSelect.locator('option').nth(1).textContent();
    await savedSelect.selectOption({ label: label! });
    await dialog.getByRole('button', { name: '删除模型连接', exact: true }).click();
    await dialog.getByRole('button', { name: '确认删除连接', exact: true }).click();
    await expect(savedSelect.locator('option')).toHaveCount(options - 1, { timeout: 15_000 });
  }
  await dialog.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  // History stays readable and the composer offers a real reconnect path.
  await expect(page.locator('.ns-composer')).toBeVisible();
  await expect(page.locator('.ns-history')).toBeVisible();
  const connectLink = page.getByRole('button', { name: '连接模型', exact: true });
  if (await connectLink.count()) await expect(connectLink).toBeVisible();
});
