import { expect, test } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

test.skip(!process.env.KNORVIA_UI_FIXTURE_WORKSPACE, 'Requires isolated native gateway');
test('Chrome: upload, order, frame, export and reopen personal-library videos', async ({ page }, info) => {
  test.setTimeout(120000);
  const title = `Chrome 已有素材剪辑 ${Date.now()}`;
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('knorvia-language', 'zh'));
  await page.setViewportSize({ width: 1280, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  const source = path.join(process.env.KNORVIA_UI_FIXTURE_WORKSPACE!, '浏览器视频.mp4');
  fs.mkdirSync(path.dirname(source), { recursive: true });
  execFileSync(path.join(process.env.KNORVIA_FFMPEG_DIR!, 'ffmpeg.exe'), ['-v', 'error', '-f', 'lavfi', '-i', 'color=c=teal:s=160x90:r=30:d=1', '-c:v', 'libopenh264', '-an', '-y', source], { windowsHide: true });
  await page.getByRole('button', { name: '剪辑已有素材', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByRole('textbox', { name: '成片名称', exact: true }).fill(title);
  const secondSource = path.join(path.dirname(source), '第二段.mp4'); fs.copyFileSync(source, secondSource);
  await dialog.locator('input[type=file]').setInputFiles([source, secondSource]);
  await expect(dialog.getByRole('button', { name: '开始剪辑', exact: true })).toBeEnabled();
  await expect(dialog.locator('.ns-edit-library-order li')).toHaveCount(2);
  await dialog.getByRole('button', { name: '前移素材', exact: true }).nth(1).click();
  await expect(dialog.locator('.ns-edit-library-order li').first()).toContainText('第二段.mp4');
  await page.screenshot({ path: info.outputPath('library-import.png'), animations: 'disabled' });
  await dialog.getByRole('button', { name: '开始剪辑', exact: true }).click();
  dialog = page.getByRole('dialog');
  await expect(dialog.locator('.ns-timeline')).toBeVisible();
  await expect(dialog.locator('.ns-timeline-shot').first()).toContainText('第二段.mp4');
  await expect(dialog.locator('video')).toBeVisible();
  await expect.poll(() => dialog.locator('video').evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  await dialog.getByLabel('画面适配', { exact: true }).selectOption('cover');
  await dialog.getByLabel('顺时针旋转', { exact: true }).selectOption('90');
  await dialog.getByLabel('水平镜像', { exact: true }).selectOption('on');
  await dialog.getByRole('button', { name: '保存剪辑', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '保存剪辑', exact: true })).toBeDisabled();
  await page.screenshot({ path: info.outputPath('library-edit-wide.png'), animations: 'disabled' });
  await dialog.getByRole('button', { name: '导出 MP4', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '查看成片', exact: true })).toBeVisible({ timeout: 30000 });
  await dialog.getByRole('button', { name: '查看成片', exact: true }).click();
  await expect.poll(() => dialog.locator('video').evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: '剪辑已有素材', exact: true }).click();
  await page.getByText('继续已有剪辑', { exact: true }).click();
  await page.getByRole('button', { name: title, exact: true }).click();
  await expect(dialog.getByLabel('顺时针旋转', { exact: true })).toHaveValue('90');
  await expect(dialog.getByLabel('画面适配', { exact: true })).toHaveValue('cover');
  await page.setViewportSize({ width: 480, height: 900 });
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.evaluate(() => { localStorage.setItem('knorvia-theme', 'dark'); window.dispatchEvent(new StorageEvent('storage', { key: 'knorvia-theme', newValue: 'dark' })); });
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.screenshot({ path: info.outputPath('library-edit-narrow-dark.png'), animations: 'disabled' });
  expect(errors).toEqual([]);
});
