import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const evidence = process.env.KNORVIA_WHISPER_EVIDENCE;
test.skip(!evidence, 'Requires isolated real-Whisper acceptance home');
test('Chrome: real automatic captions apply, export and render', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => { localStorage.setItem('knorvia-language', 'zh'); });
  await page.setViewportSize({ width: 1280, height: 1000 });
  await page.goto('/workbench/studio');
  await expect(page.locator('.nw-connection')).toHaveClass(/is-connected/);
  await page.locator('.ns-sequence-toggle').click();
  await page.getByRole('button', { name: 'Real english', exact: false }).click();
  await page.getByRole('button', { name: '剪辑成片', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.locator('.ns-subtitles > summary').first().click();
  await dialog.getByRole('button', { name: '自动识别字幕', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '取消识别', exact: true })).toBeVisible();
  await expect(dialog.getByRole('button', { name: '应用到剪辑', exact: true })).toBeEnabled({ timeout: 45000 });
  await dialog.getByRole('button', { name: '应用到剪辑', exact: true }).click();
  await expect(dialog.getByLabel('字幕内容', { exact: true }).first()).toHaveValue(/fox/);
  await dialog.getByRole('button', { name: '导出 MP4', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '导出 MP4', exact: true })).toBeEnabled({ timeout: 30000 });
  await expect(dialog.getByText('成片已存入资料库', { exact: false })).toBeVisible({ timeout: 30000 });
  await dialog.getByRole('button', { name: '查看成片', exact: true }).click();
  const video = dialog.getByLabel('成片预览', { exact: true });
  await video.scrollIntoViewIfNeeded();
  fs.writeFileSync(path.join(evidence!, 'chrome-tracks-initial.json'), JSON.stringify(await video.evaluate((v: HTMLVideoElement) => ({ src: v.src, ready: v.readyState, network: v.networkState, error: v.error?.message, tracks: Array.from(v.textTracks).map(t => ({ label: t.label, mode: t.mode, cues: t.cues?.length })) }))));
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2);
  fs.writeFileSync(path.join(evidence!, 'chrome-tracks.json'), JSON.stringify(await video.evaluate((v: HTMLVideoElement) => ({ src: v.src, ready: v.readyState, tracks: Array.from(v.textTracks).map(t => ({ label: t.label, mode: t.mode, cues: t.cues?.length })) }))));
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => Array.from(v.textTracks).some(t => t.mode === 'showing' && !!t.cues?.length))).toBe(true);
  await video.evaluate((v: HTMLVideoElement) => { v.currentTime = 1; });
  await video.evaluate((v: HTMLVideoElement) => new Promise<void>((resolve, reject) => { v.requestVideoFrameCallback(() => { v.pause(); resolve(); }); void v.play().catch(reject); }));
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => Array.from(v.textTracks).some(t => !!t.activeCues?.length))).toBe(true);
  await page.screenshot({ path: path.join(evidence!, 'chrome-real-captions.png') });
  expect(errors).toEqual([]);
  fs.writeFileSync(path.join(evidence!, 'chrome-result.json'), JSON.stringify({ passed: true, at: new Date().toISOString(), errors }));
});
