const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),repo=path.resolve(root,'..');
const React=require(path.join(repo,'web/node_modules/react'));
const {renderToStaticMarkup}=require(path.join(repo,'web/node_modules/react-dom/server'));
const icons=require(path.join(repo,'web/node_modules/lucide-react'));
const icon=name=>renderToStaticMarkup(React.createElement(icons[name],{'aria-hidden':true,focusable:false,strokeWidth:1.6}));
const G='https://github.com/accomplish-zrh/Knorvia';
const external=(href,label)=>`<a href="${href}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const screens=[['conversation','对话','对话与任务','Knorvia 真实对话工作台，左侧按项目组织任务，底部输入想法','MessageSquare'],['library','资料','个人资料库','个人资料库中打开的创作手记，可查看和编辑','FolderOpen'],['studio','创作','图片与视频创作台','Knorvia 创作台的图片视频模式、参考画面与镜头队列','Clapperboard'],['bots','Bots','你的 Bot 伙伴','映像助手 Bot 的真实设置与对话入口','Bot'],['memory','记忆','可整理的个人记忆','查看和管理已保存的记忆','Brain']];
const capabilities=[['你的模型，你来选。','保存多个提供商，为对话、图片和视频选择合适的模型。也可以连接自己的本地模型。',['多提供商','独立配置','本地模型'],'SlidersHorizontal'],['让资料成为下一次的起点。','个人资料与创作成果统一收好。查看、编辑、整理，也可以交给 Agent 一起完成。',['个人资料库','内容预览','可编辑'],'Library'],['为每个角色，留一个位置。','创建有各自角色与上下文的 Bot。单独交流，或组成群聊，让不同擅长的伙伴协作。',['Soul 设定','独立上下文','群聊协作'],'Bot'],['记住什么，由你决定。','看见已保存的记忆，按需要修改或删除。让长期使用积累下来的内容保持清晰。',['可视化记忆','随时整理'],'Brain'],['能力，随需要生长。','用 Skill 和插件接入学习、研究与创作方法；用 CLI 与外部工具衔接，让重复工作成为自动化。',['Skill / 插件','CLI','自动化'],'Blocks']];
const faqs=[['下载后如何开始？','运行 Windows 安装包，或完整解压便携包后启动 Knorvia.exe。在设置中连接自己的模型服务商，然后选择项目，开始第一段对话。'],['模型调用如何收费？','Knorvia 客户端不内置钱包或订阅。在线模型的额度、能力和费用由你连接的服务商决定；本地模型按自己的运行环境使用。'],['资料存在哪里？','资料、项目和工作记录由本地工作台管理。使用在线模型、插件或联网工具时，请求所需内容会发送到对应的服务。你可以按自己的需要选择连接。'],['可以参与改进吗？',`可以。在 GitHub 查看源码、提交问题或参与贡献。项目采用 Apache-2.0 开源许可，第三方依赖遵循各自许可。${external(G+'/blob/main/CONTRIBUTING.md','阅读贡献指南 ↗')}`]];
const nav='<a href="#workbench">工作台</a><a href="#creation">创作</a><a href="#capabilities">无限可能</a>';
const html=`<!doctype html>
<html lang="zh-CN"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Knorvia · 让想法，立起来。</title>
<meta name="description" content="Knorvia 是你的个人 AI 工作台。连接模型、资料与工具，从一句想法走到文档、图片、视频和真正完成的工作。">
<meta name="theme-color" content="#111515"><meta name="color-scheme" content="dark"><link rel="canonical" href="https://knorvia.xyz/">
<meta property="og:title" content="Knorvia · 让想法，立起来。"><meta property="og:description" content="对话、资料、创作与 Bots，在一张属于你的工作台上。"><meta property="og:type" content="website"><meta property="og:url" content="https://knorvia.xyz/"><meta property="og:locale" content="zh_CN"><meta property="og:image" content="https://knorvia.xyz/assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="favicon.ico" sizes="any"><link rel="apple-touch-icon" href="assets/brand.png"><link rel="preload" href="assets/fonts/geist-400.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="styles.css?v=20260909-3"><script src="assets/gsap.min.js" defer></script><script src="assets/ScrollTrigger.min.js" defer></script><script src="app.js?v=20260909-3" defer></script><script type="module" src="sculpture.js?v=20260909-3"></script>
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:'Knorvia',url:'https://knorvia.xyz/',applicationCategory:'ProductivityApplication',operatingSystem:'Windows',license:G+'/blob/main/LICENSE',downloadUrl:G+'/releases/latest'})}</script>
</head><body>
<a class="skip-link" href="#main">跳到主要内容</a>
<header class="site-header"><a class="brand" href="#hero" aria-label="Knorvia 首页"><img src="assets/brand.png" width="34" height="34" alt=""><span>Knorvia</span></a><nav class="desktop-nav" aria-label="主导航">${nav}</nav><div class="header-actions"><a class="source-link" href="${G}" target="_blank" rel="noopener noreferrer" aria-label="在 GitHub 查看源码">${icon('Github')}</a><a class="button compact silver" href="#install">开始使用 <span aria-hidden="true">↗</span></a><button class="menu-toggle icon-button" aria-expanded="false" aria-controls="mobile-menu" aria-label="打开导航">${icon('Menu')}</button></div><nav class="mobile-nav" id="mobile-menu" aria-label="移动导航" hidden>${nav}<a href="#install">开始使用</a></nav></header>
<main id="main">
<section class="hero" id="hero" aria-labelledby="hero-title"><div class="hero-light" aria-hidden="true"></div><div class="hero-copy"><p class="eyebrow enter"><span class="status-dot"></span>你的个人 AI 工作台</p><h1 id="hero-title"><span class="hero-line enter">让想法，</span><span class="hero-line enter">立起来<span class="jade">。</span></span></h1><p class="hero-description enter">一句话，打开更多可能。<br>连接你的模型、资料与工具，<br>把思考做成真正的作品。</p><div class="hero-actions enter"><a class="button silver" href="#install">开始使用 ${icon('ArrowUpRight')}</a><a class="text-link" href="#workbench">向下探索 ${icon('ArrowDown')}</a></div></div>
<div class="sculpture-scene" id="sculpture-scene" role="img" aria-label="由银色与青色金属带构成的立体 Knorvia 装置，可用下方按钮切换材质"><img class="sculpture-fallback" src="assets/brand-sculpture.webp" width="1100" height="1230" fetchpriority="high" alt="Knorvia 的立体折叠 K 标识"><canvas id="sculpture-canvas" aria-hidden="true"></canvas></div>
<div class="material-controls" hidden><span class="material-label">换一种质感</span><div role="group" aria-label="切换立体装置材质">${[['titanium','银钛','titanium'],['carbon','石墨','carbon'],['jade','青玉','emerald']].map(([id,label,c],i)=>`<button class="material-choice" data-material="${id}" aria-pressed="${i===0}" aria-label="${label}材质" title="${label}"><i class="swatch ${c}"></i></button>`).join('')}</div><button class="motion-toggle icon-button" aria-pressed="false" aria-label="暂停装置动效" title="暂停装置动效">${icon('Pause')}</button></div>
<span class="hero-wordmark" aria-hidden="true">knorvia</span><div class="hero-bottom"><span>为好奇心，留一整个工作空间。</span><a href="#workbench" aria-label="探索工作台">${icon('ArrowDown')}</a><span>LOCAL FIRST. OPEN BY DESIGN.</span></div></section>
<section class="workbench section" id="workbench" aria-labelledby="workbench-title"><header class="section-heading shell reveal"><p class="eyebrow">01 / 展开你的工作</p><div class="heading-split"><h2 id="workbench-title">从对话出发。<br><span class="muted-heading">在同一个地方，做完。</span></h2><p>想法、资料、工具与成果，<br>本来就该在一起。<br>把切换窗口的时间，留给专注。</p></div></header>
<div class="workbench-showcase" data-showcase><div class="showcase-top shell"><span class="story-counter"><b id="story-number">01</b> / 05</span><p id="story-heading">把一句想法，交给工作台。</p><a class="story-skip" href="#creation">跳过演示 <span aria-hidden="true">↗</span></a></div><div class="preview-stage">
${screens.map(([id,label,title,alt],i)=>`<div id="panel-${id}" class="preview-panel" role="tabpanel" aria-labelledby="tab-${id}" tabindex="0" ${i?'hidden':''}><button class="screen-zoom" data-zoom="assets/${id}-1440.webp" data-caption="${title}" aria-label="放大${title}画面"><img src="assets/${id}-1440.webp" srcset="assets/${id}-720.webp 720w, assets/${id}-1440.webp 1440w" sizes="(max-width: 767px) 94vw, 82vw" width="1440" height="960" loading="lazy" alt="${alt}"><span class="zoom-cue">${icon('Expand')}</span></button></div>`).join('')}
</div><div class="showcase-bottom shell"><div class="preview-tabs" role="tablist" aria-label="选择工作台画面">${screens.map(([id,label,title,alt,glyph],i)=>`<button id="tab-${id}" role="tab" aria-selected="${i===0}" aria-controls="panel-${id}" tabindex="${i?-1:0}" data-screen="${id}">${icon(glyph)}${label}</button>`).join('')}</div><p class="preview-note">开发版实机画面 · 点击可放大</p></div><div class="story-track" aria-hidden="true"><span></span></div></div><p class="preview-description shell" id="preview-description">按项目整理任务，在对话里推进目标，让文件、工具和预览始终在手边。</p></section>
<section class="creation section shell" id="creation" aria-labelledby="creation-title"><header class="section-heading reveal"><p class="eyebrow">02 / 把灵感，接成作品</p><div class="heading-split"><h2 id="creation-title">下一帧，<br>接着你的想象。</h2><p>从参考图到镜头，从镜头到短片。<br>让素材与提示词在同一条工作流中，<br>顺着灵感向前。</p></div></header><div class="creation-grid"><div class="frame-art reveal" aria-label="视频镜头衔接示意"><div class="frame-scene" data-mood-scene="morning"><div class="film-grain"></div><div class="scene-sun"></div><div class="scene-horizon"></div><div class="scene-arch arch-back"></div><div class="scene-arch arch-front"></div><div class="scene-floor"></div><span class="frame-label">镜头氛围预览</span><span class="frame-corner">16:9</span></div><div class="film-connection"><span>上一镜的尾帧</span><div><i></i>${icon('ArrowRight')}<i></i></div><span>下一镜的首帧</span></div><div class="frame-secondary"><div class="mini-frame"><div class="mini-sun"></div></div><div><span class="eyebrow">让镜头接得上</span><p>自动提取尾帧。<br>把连续性留给工作流。</p></div></div></div><div class="creation-copy reveal"><h3>先给想法一点氛围。</h3><p>选一个光线，写下你看到的世界。<br>把这段提示词带进 Knorvia，接着创作。</p><div class="prompt-options" role="group" aria-label="选择镜头氛围"><button aria-pressed="true" data-mood="morning">晨光</button><button aria-pressed="false" data-mood="rain">雨后</button><button aria-pressed="false" data-mood="night">夜色</button></div><p id="prompt-result" aria-live="polite">清晨，薄雾里的弧形建筑被第一束日光照亮。柔和银绿色，细腻材质，镜头缓慢推进，安静而开阔。</p><button class="copy-prompt text-link">复制这段提示词 ${icon('Copy')}</button><span class="copy-status" role="status"></span><p class="creation-note">这里是交互示意，不会调用模型。<br>实际生成能力取决于你连接的服务商。</p></div></div><div class="creation-features">${[['Images','从一张参考图开始','带着画面创作，让构图、角色和风格有据可循。'],['ListVideo','让分镜排好队','通用提示词贯穿镜头，按顺序生成，延续上一个画面。'],['Workflow','把工作流接进来','图片、视频与附加创作流程联动，保留每一步的素材。']].map(([ic,title,body])=>`<article class="reveal">${icon(ic)}<h3>${title}</h3><p>${body}</p></article>`).join('')}</div></section>
<section class="capabilities section shell" id="capabilities" aria-labelledby="capabilities-title"><div class="capability-intro reveal"><p class="eyebrow">03 / 留给你的自由</p><h2 id="capabilities-title">一张工作台。<br><span class="muted-heading">不止一种<br>可能。</span></h2><p>让工具适应你的工作。<br>也给下一个想法，留好位置。</p><div class="connection-object" aria-hidden="true"><div class="connection-ring ring-one"></div><div class="connection-ring ring-two"></div><img src="assets/brand.png" width="90" height="90" loading="lazy" alt=""></div></div><div class="capability-list">${capabilities.map(([title,body,tags,ic],i)=>`<article class="capability reveal"><span class="capability-number">0${i+1}</span><div><h3>${title}</h3><p>${body}</p><div class="feature-tags">${tags.map(t=>`<span>${t}</span>`).join('')}</div></div>${icon(ic)}</article>`).join('')}</div></section>
<section class="ownership section shell" aria-labelledby="ownership-title"><p class="eyebrow reveal">属于你的空间</p><h2 class="ownership-statement reveal" id="ownership-title">模型可以不同。<br>想法始终<span class="jade">属于你。</span></h2><div class="ownership-bottom"><p>Knorvia 采用本地优先的工作方式。<br>资料、项目与工作记录，在自己的电脑上管理。</p><p>调用在线模型和联网工具时，<br>相关内容会发送给你配置的服务。</p><a class="text-link" href="${G}" target="_blank" rel="noopener noreferrer">打开源码，看看里面 ${icon('ArrowUpRight')}</a></div></section>
<section class="install section shell" id="install" aria-labelledby="install-title"><div class="download-block reveal"><p class="eyebrow">从下一件想做的事开始</p><h2 id="install-title">轮到你的<br><span class="muted-heading">想法了。</span></h2><div class="download-actions"><a class="button silver" href="${G}/releases/download/v1.0.0/Knorvia-1.0.0-setup.exe">${icon('Download')}下载 Windows 版</a><a class="text-link" href="${G}/releases/download/v1.0.0/Knorvia-1.0.0-portable.zip">便携版 ${icon('ArrowUpRight')}</a></div><a class="release-link" href="${G}/releases/latest" target="_blank" rel="noopener noreferrer">公开发行 v1.0.0 · 发行说明与校验文件 ↗</a><p class="release-note">上方展示开发版实机画面。<br>公开版本功能以发行说明为准。</p></div><div class="faq reveal" aria-label="使用前了解"><h3>你可能还想知道</h3>${faqs.map(([q,a])=>`<details><summary>${q}${icon('Plus')}</summary><div><p>${a}</p></div></details>`).join('')}</div></section>
</main><footer class="site-footer shell"><div class="footer-top"><a class="brand" href="#hero"><img src="assets/brand.png" width="32" height="32" alt=""><span>Knorvia</span></a><p>为热爱学习与创作的人而作。</p><a class="back-top text-link" href="#hero">回到顶部 ${icon('ArrowUp')}</a></div><div class="footer-bottom"><span>© 2026 Knorvia</span><nav aria-label="资源与法律信息">${external(G,'GitHub')}${external('https://api.knorvia.xyz','中转服务')}${external('https://pay.ldxp.cn/shop/knorvia.ai','小铺')}${external(G+'/blob/main/THIRD_PARTY_NOTICES.md','第三方声明')}${external(G+'/blob/main/LICENSE','Apache-2.0')}</nav></div><div class="footer-wordmark" aria-hidden="true">knorvia</div></footer>
<dialog class="media-dialog" id="image-dialog" aria-labelledby="image-dialog-title"><div class="dialog-bar"><h2 id="image-dialog-title">工作台预览</h2><button class="icon-button" data-close-dialog aria-label="关闭预览">${icon('X')}</button></div><div class="zoom-content"><img id="zoom-image" width="1440" height="960" alt=""></div></dialog>
<noscript><style>.preview-tabs,.menu-toggle,.material-controls,.story-skip,.prompt-options,.copy-prompt{display:none!important}.preview-panel[hidden]{display:block!important;margin-top:24px}.mobile-nav[hidden]{display:flex}.screen-zoom{pointer-events:none}.zoom-cue{display:none}</style></noscript>
</body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html.replace(icon('Pause'),`<span class="pause-glyph">${icon('Pause')}</span><span class="play-glyph" hidden>${icon('Play')}</span>`));
fs.copyFileSync(path.join(root,'node_modules/three/build/three.module.js'),path.join(root,'assets/three.module.js'));
const env=fs.readFileSync(path.join(root,'node_modules/three/examples/jsm/environments/RoomEnvironment.js'),'utf8').replace("from 'three'","from './three.module.js'");
fs.writeFileSync(path.join(root,'assets/RoomEnvironment.js'),env);
fs.copyFileSync(path.join(root,'node_modules/three/LICENSE'),path.join(root,'assets/THREE-LICENSE.txt'));
console.log('Static product site and matching Three.js runtime built.');
