const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../../web/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../work/product-site-20260909/acceptance');fs.mkdirSync(out,{recursive:true});
const base=process.env.SITE_URL||'http://127.0.0.1:4490';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const results=[];try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-CN',permissions:['clipboard-read','clipboard-write']});
 await context.addInitScript(()=>{window.__draws=0;for(const C of [window.WebGLRenderingContext,window.WebGL2RenderingContext]){if(!C)continue;for(const name of ['drawElements','drawArrays']){const original=C.prototype[name];C.prototype[name]=function(...args){window.__draws++;return original.apply(this,args);};}}});
 const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 await p.goto(base,{waitUntil:'networkidle'});await p.locator('#sculpture-scene.ready').waitFor();await p.waitForTimeout(1300);await p.screenshot({path:path.join(out,'desktop-1440.png')});
 await p.locator('.motion-toggle').click();await p.waitForTimeout(700);let draws=await p.evaluate(()=>window.__draws);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>window.__draws),draws,'paused scene should stop drawing');results.push('WebGL render pauses at rest');
 for(const material of ['carbon','jade','titanium']){await p.locator(`[data-material="${material}"]`).click();assert.equal(await p.locator(`[data-material="${material}"]`).getAttribute('aria-pressed'),'true');}results.push('three material controls');
 const st=await p.evaluate(()=>{const s=ScrollTrigger.getAll().find(t=>t.vars.pin);return{start:s.start,end:s.end};});
 for(const [i,t] of [0.04,.3,.51,.75,.96].entries()){await p.evaluate(y=>scrollTo({top:y,behavior:'instant'}),st.start+(st.end-st.start)*t);await p.waitForTimeout(1000);assert.equal(await p.locator('[role="tab"][aria-selected="true"]').count(),1);if(i===2){await p.screenshot({path:path.join(out,'scroll-studio.png')});await p.locator('#panel-studio .screen-zoom').click();assert.equal(await p.locator('#image-dialog').evaluate(d=>d.open),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#image-dialog').evaluate(d=>d.open),false);}}
 await p.locator('#tab-library').focus();await p.keyboard.press('End');await p.waitForTimeout(1600);assert.equal(await p.locator('#tab-memory').getAttribute('aria-selected'),'true');results.push('pinned sequence, reverse/tab navigation and preview dialog');
 await p.locator('.story-skip').click();await p.waitForTimeout(1400);assert(await p.locator('#creation').evaluate(e=>e.getBoundingClientRect().top<innerHeight));await p.locator('[data-mood="night"]').click();await p.waitForTimeout(950);assert((await p.locator('#prompt-result').innerText()).includes('夜色'));await p.locator('.copy-prompt').click();assert((await p.locator('.copy-status').innerText()).includes('已复制'));await p.screenshot({path:path.join(out,'creation-night.png')});results.push('lighting preview and prompt clipboard');
 await p.locator('.faq summary').first().click();await p.waitForTimeout(500);assert(await p.locator('.faq details').first().evaluate(d=>d.open));await p.locator('.faq summary').first().click();await p.waitForTimeout(500);assert(!(await p.locator('.faq details').first().evaluate(d=>d.open)));results.push('FAQ open/close');
 for(const width of [320,390,768,1024,1920]){await p.setViewportSize({width,height:width<768?844:1000});await p.goto(base,{waitUntil:'networkidle'});await p.waitForTimeout(850);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`horizontal overflow ${width}`);if(width===390){await p.screenshot({path:path.join(out,'mobile-390.png')});await p.locator('.menu-toggle').click();assert(await p.locator('#mobile-menu').isVisible());await p.keyboard.press('Escape');assert(!(await p.locator('#mobile-menu').isVisible()));await p.locator('#tab-bots').click();assert.equal(await p.locator('#tab-bots').getAttribute('aria-selected'),'true');}results.push(`viewport ${width}`);}
 await p.setViewportSize({width:1440,height:900});await p.emulateMedia({reducedMotion:'reduce'});await p.goto(base,{waitUntil:'networkidle'});assert.equal(await p.locator('.scroll-story').count(),0);await p.locator('#tab-memory').click();assert(await p.locator('#panel-memory').isVisible());results.push('reduced motion removes scroll pin; all tabs remain usable');
 assert.equal(errors.length,0,JSON.stringify(errors));results.push('no console page errors or missing resources');
 const fallback=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:false});const fp=await fallback.newPage();await fp.goto(base);assert(await fp.locator('h1').isVisible());assert.equal(await fp.locator('.preview-panel:visible').count(),5);results.push('no JavaScript: full content and five screens remain visible');await fallback.close();
 const blocked=await browser.newContext({viewport:{width:1440,height:900}});const bp=await blocked.newPage();await bp.route('**/assets/three.module.js',r=>r.abort());await bp.goto(base,{waitUntil:'networkidle'});assert(await bp.locator('.sculpture-fallback').isVisible());assert(await bp.locator('h1').isVisible());assert(!(await bp.locator('.material-controls').isVisible()));results.push('3D loading failure retains brand image and usable page');await blocked.close();
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({url:base,date:new Date().toISOString(),passed:results.length,results,errors},null,2));console.log(JSON.stringify({passed:results.length,results}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
