const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),release=process.argv[2];if(!/^\d{8}-\d+$/.test(release||''))throw Error('Pass a release id such as 20260909-6');
const output=path.resolve(root,'../work/product-orbit-20260909/deploy-'+release);if(fs.existsSync(output))throw Error('Package directory already exists; use a new candidate id');
const base='/r/'+release+'/',files=['orbit.css','orbit-app.js','orbit-scene.js','orbit-objects.js','orbit-water.js','orbit-life.js','orbit-textures.js','favicon.ico','assets/brand.png','assets/brand-relief.webp','assets/social-preview.png','assets/fonts/geist-400.woff2','assets/fonts/geist-600.woff2','assets/fonts/knorvia-hand.woff2','assets/WENKAI-LICENSE.txt','assets/three.module.js','assets/LUCIDE-LICENSE.txt','assets/THREE-LICENSE.txt','assets/GEIST-LICENSE.txt'];
for(const name of ['conversation','library','studio','bots','memory'])for(const width of [720,1440])files.push(`assets/${name}-${width}.webp`);
for(const name of ['workspace','images','videos','library','bots','memory'])files.push(`assets/orbit/${name}.webp`);
for(const f of files){const dest=path.join(output,'r',release,f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,f),dest);}
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');html=html.replace(/(src|href)="((?:assets\/|orbit\.css|orbit-app\.js|favicon\.ico)[^"]*)"/g,(_,a,f)=>`${a}="${base}${f}"`).replace('https://knorvia.xyz/assets/social-preview.png','https://knorvia.xyz'+base+'assets/social-preview.png');
fs.writeFileSync(path.join(output,'index.html'),html);for(const f of ['robots.txt','sitemap.xml'])fs.copyFileSync(path.join(root,f),path.join(output,f));
const names=['index.html','robots.txt','sitemap.xml',...files.map(f=>'r/'+release+'/'+f)];const manifest=names.map(f=>({file:f,bytes:fs.statSync(path.join(output,f)).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(output,f))).digest('hex')}));
fs.writeFileSync(path.join(output,'SHA256SUMS'),manifest.map(f=>f.sha256+'  '+f.file).join('\n')+'\n');fs.writeFileSync(path.join(output,'MANIFEST.json'),JSON.stringify({release,totalBytes:manifest.reduce((s,f)=>s+f.bytes,0),files:manifest},null,2));console.log(JSON.stringify({output,release,files:names.length,totalBytes:manifest.reduce((s,f)=>s+f.bytes,0)}));
