'use client';
import { useCallback, useEffect, useState } from 'react';
import { ArrowDownToLine, Check, ChevronDown, FolderOpen, Github, History, Loader2, Package, Plus, Power, Trash2 } from 'lucide-react';
import { errorText, useWorkbench } from './NativeWorkbenchProvider';
import { Modal } from './WorkbenchShell';
import './extension-manager.css';

type Source = { type: 'local'; workspaceId: string; path: string } | { type: 'github'; repository: string; commit: string; subdirectory?: string };
type Report = { format: string; status: string; components: { component: string; format: string; status: string; details: string; name?: string }[] };
type Entry = { id: string; name: string; revision: number; enabled: boolean; activeVersion: string; report: Report; recoveryError?: string; versions: { id: string; createdAt: string; sha256: string; source: Partial<Source> }[] };
type Inspection = { sha256: string; files: number; bytes: number; report: Report };

export function ExtensionManager({ workspaceId: requestedWorkspace }: { workspaceId?: string }) {
  const { request, t, workspaces, workspaceId, connection } = useWorkbench();
  const [entries, setEntries] = useState<Entry[]>([]), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [recoveryError, setRecoveryError] = useState('');
  const [importing, setImporting] = useState(false), [updating, setUpdating] = useState<Entry>(), [removing, setRemoving] = useState<Entry>();
  const [history, setHistory] = useState<Entry>(), [version, setVersion] = useState('');
  const [sourceType, setSourceType] = useState<'local' | 'github'>('local'), [project, setProject] = useState(requestedWorkspace || workspaceId);
  const [localPath, setLocalPath] = useState(''), [repository, setRepository] = useState(''), [commit, setCommit] = useState(''), [subdirectory, setSubdirectory] = useState('');
  const [inspection, setInspection] = useState<Inspection>();
  const localProjects = workspaces.filter(p => p.cwd);
  const load = useCallback(async () => { try { const result = await request<{ entries: Entry[]; recoveryError?: string }>('extension/list', {}); setEntries(result.entries); setRecoveryError(result.recoveryError || ''); } finally { setLoading(false); } }, [request]);
  useEffect(() => { if (connection === 'connected') { setError(''); void load().catch(e => setError(errorText(e))); } }, [load, connection]);
  useEffect(() => { setInspection(undefined); }, [sourceType, project, localPath, repository, commit, subdirectory]);
  const action = async (work: () => Promise<void>) => { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const source = (): Source => sourceType === 'local' ? { type: 'local', workspaceId: project, path: localPath.trim() } : { type: 'github', repository: repository.trim(), commit: commit.trim(), subdirectory: subdirectory.trim() };
  const startImport = (entry?: Entry) => {
    setUpdating(entry); setInspection(undefined); setError(''); setProject(localProjects.find(p => p.id === (requestedWorkspace || workspaceId))?.id || localProjects[0]?.id || ''); setLocalPath('');
    const prior = entry?.versions.find(v => v.id === entry.activeVersion)?.source;
    setSourceType(prior?.type === 'github' ? 'github' : 'local'); setRepository(prior && 'repository' in prior ? prior.repository || '' : ''); setCommit(''); setSubdirectory(prior && 'subdirectory' in prior ? prior.subdirectory || '' : ''); setImporting(true);
  };
  const status = (value: string) => ({ loadable: t('可装载', 'Loadable'), 'convertible-partial': t('部分可用', 'Partly supported'), unsupported: t('不支持', 'Unsupported'), 'missing-dependency': t('需要运行环境', 'Runtime required'), 'unverified-execution': t('待连接验证', 'Connection unverified') }[value] || value);
  const table = (report: Report) => <div className="nw-extension-components">{report.components.map((component, i) => <div key={`${component.component}-${i}`}><span><strong>{component.name || component.component}</strong><small>{component.format}</small></span><span className="nw-extension-status" data-status={component.status}>{status(component.status)}</span><details><summary>{t('说明', 'Details')}</summary><p>{component.details}</p></details></div>)}</div>;
  return <section className="nw-extension-manager" aria-label={t('管理扩展', 'Manage extensions')}>
    <div className="nw-page-heading"><div><h1>{t('已安装扩展', 'Installed extensions')}</h1><p>{t('添加 Skill 或插件，按需启用，也可以回到之前的版本。', 'Add a Skill or plugin, enable it when needed, or return to an earlier version.')}</p></div><button className="nw-button" disabled={busy} onClick={() => startImport()}><Plus size={15} />{t('添加扩展', 'Add extension')}</button></div>
    {recoveryError && <p className="nw-inline-error" role="alert">{recoveryError}</p>}{entries.filter(entry => entry.recoveryError).map(entry => <p className="nw-inline-error" key={entry.id} role="alert">{entry.name}: {entry.recoveryError}</p>)}{error && <p className="nw-inline-error" role="alert">{error}</p>}{notice && <p role="status" className="nw-extension-notice"><Check size={16} />{notice}</p>}
    {!entries.length && <div className="nw-extension-empty" role={loading ? 'status' : undefined}>{loading && connection === 'connected' ? <Loader2 size={26} className="nw-spin" /> : <Package size={28} strokeWidth={1.5} />}<strong>{loading ? connection === 'connected' ? t('正在读取扩展…', 'Loading extensions…') : t('等待连接工作引擎', 'Waiting for the engine') : t('还没有安装扩展', 'No extensions installed yet')}</strong><p>{t('从项目文件夹、ZIP 或固定 GitHub 版本添加扩展。', 'Import an extension from a project folder, ZIP, or fixed GitHub version.')}</p></div>}
    {entries.map(entry => <article className="nw-extension-entry" key={entry.id}><header><Package size={18} /><div><strong>{entry.name}</strong><small>{entry.enabled ? t('已启用', 'Enabled') : t('已停用', 'Disabled')} · {status(entry.report.status)}</small></div><button className="nw-button" disabled={busy} aria-pressed={entry.enabled} onClick={() => void action(async () => { await request('extension/enable', { id: entry.id, revision: entry.revision, enabled: !entry.enabled }); setNotice(entry.enabled ? t('扩展已停用。', 'Extension disabled.') : t('扩展已启用，技能列表已刷新。', 'Extension enabled and Skills refreshed.')); })}><Power size={14} />{entry.enabled ? t('停用', 'Disable') : t('启用', 'Enable')}</button></header><details><summary>{t('包含的能力', 'Included capabilities')}<ChevronDown size={14} /></summary>{table(entry.report)}</details><footer><button className="nw-button" disabled={busy} onClick={() => startImport(entry)}><ArrowDownToLine size={14} />{t('更新', 'Update')}</button><button className="nw-button" disabled={busy || entry.versions.length < 2} onClick={() => { setHistory(entry); setVersion(entry.versions.find(v => v.id !== entry.activeVersion)?.id || ''); }}><History size={14} />{t('历史版本', 'Versions')}</button><button className="nw-icon" disabled={busy} aria-label={t('卸载扩展', 'Uninstall extension')} onClick={() => setRemoving(entry)}><Trash2 size={15} /></button></footer></article>)}
    {importing && <Modal title={updating ? t('更新扩展', 'Update extension') : t('添加扩展', 'Add extension')} close={() => setImporting(false)} busy={busy}><div className="nw-extension-import">
      <div className="nw-tabs"><button className={sourceType === 'local' ? 'is-active' : ''} disabled={busy} onClick={() => setSourceType('local')}><FolderOpen size={15} />{t('本地文件', 'Local files')}</button><button className={sourceType === 'github' ? 'is-active' : ''} disabled={busy} onClick={() => setSourceType('github')}><Github size={15} />{t('GitHub', 'GitHub')}</button></div>
      {sourceType === 'local' ? <><label className="nw-field">{t('项目', 'Project')}<select aria-label={t('项目', 'Project')} disabled={busy} value={project} onChange={e => setProject(e.target.value)}><option value="">{t('选择项目', 'Choose project')}</option>{localProjects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="nw-field">{t('项目内的文件夹或 ZIP 路径', 'Folder or ZIP path within the project')}<input disabled={busy} placeholder={t('extensions/my-skill', 'extensions/my-skill')} value={localPath} onChange={e => setLocalPath(e.target.value)} /></label><p className="nw-help">{localProjects.length ? t('留空可检查项目根目录。导入会保留原文件。', 'Leave the path empty to inspect the project root. Importing preserves the original files.') : t('先在侧栏新建项目并选择本地文件夹，再从中导入扩展。也可切换到 GitHub。', 'Create a project with a local folder in the sidebar before importing files, or switch to GitHub.')}</p></> : <><label className="nw-field">{t('仓库', 'Repository')}<input disabled={busy} placeholder={t('owner/repository', 'owner/repository')} value={repository} onChange={e => setRepository(e.target.value)} /></label><label className="nw-field">{t('固定版本（完整提交 SHA）', 'Fixed version (full commit SHA)')}<input disabled={busy} minLength={40} maxLength={40} value={commit} onChange={e => setCommit(e.target.value)} /></label><label className="nw-field">{t('仓库内的扩展目录（可选）', 'Extension folder in the repository (optional)')}<input disabled={busy} value={subdirectory} onChange={e => setSubdirectory(e.target.value)} /></label></>}
      {inspection && <><p className="nw-help">{inspection.files} {t('个文件', 'files')} · {(inspection.bytes / 1024).toFixed(1)} {t('KB', 'KB')}</p>{table(inspection.report)}<p className="nw-help">{t('安装后默认停用。启用只会装载受支持的能力；Claude 专属 Hooks 不会执行。', 'New installations start disabled. Enabling loads supported capabilities; Claude-specific hooks do not run.')}</p></>}
      {error && <p className="nw-inline-error" role="alert">{error}</p>}<div className="nw-dialog-actions"><button className="nw-button" disabled={busy || (sourceType === 'local' ? !project : !repository || commit.length !== 40)} onClick={() => void action(async () => setInspection(await request<Inspection>('extension/inspect', { source: source() })))}>{busy ? <Loader2 size={14} className="nw-spin" /> : <Check size={14} />}{t('检查兼容性', 'Inspect compatibility')}</button><button className="nw-button nw-button-primary" disabled={busy || !inspection || inspection.report.status === 'unsupported'} onClick={() => void action(async () => { await request('extension/install', { source: source(), expectedSha256: inspection!.sha256, ...(updating ? { id: updating.id, revision: updating.revision } : {}) }); setImporting(false); setNotice(updating ? t('扩展已更新，可从历史版本回退。', 'Extension updated. Earlier versions remain available.') : t('扩展已安装，启用后即可使用。', 'Extension installed. Enable it to use its capabilities.')); })}>{updating ? t('更新', 'Update') : t('安装', 'Install')}</button></div>
    </div></Modal>}
    {removing && <Modal title={t('卸载扩展', 'Uninstall extension')} close={() => setRemoving(undefined)} busy={busy}><p>{t(`卸载“${removing.name}”？原始文件和已下载版本会保留，已启用的能力会移除。`, `Uninstall “${removing.name}”? Original files and downloaded versions remain; active capabilities are removed.`)}</p>{error && <p className="nw-inline-error" role="alert">{error}</p>}<div className="nw-dialog-actions"><button className="nw-button" disabled={busy} onClick={() => setRemoving(undefined)}>{t('取消', 'Cancel')}</button><button className="nw-button" disabled={busy} onClick={() => void action(async () => { await request('extension/uninstall', { id: removing.id, revision: removing.revision }); setRemoving(undefined); })}>{t('卸载', 'Uninstall')}</button></div></Modal>}
    {history && <Modal title={t('历史版本', 'Extension versions')} close={() => setHistory(undefined)} busy={busy}><label className="nw-field">{t('恢复到', 'Restore version')}<select value={version} disabled={busy} onChange={e => setVersion(e.target.value)}>{history.versions.filter(v => v.id !== history.activeVersion).map(v => <option key={v.id} value={v.id}>{new Date(v.createdAt).toLocaleString()} · {v.sha256.slice(0, 10)}</option>)}</select></label><p className="nw-help">{t('恢复所选版本，并保留当前版本供以后切换。', 'Restore this version while keeping the current version available.')}</p>{error && <p className="nw-inline-error" role="alert">{error}</p>}<button className="nw-button nw-button-primary" disabled={busy || !version} onClick={() => void action(async () => { await request('extension/rollback', { id: history.id, revision: history.revision, version }); setHistory(undefined); setNotice(t('已恢复到所选版本。', 'Selected version restored.')); })}>{t('恢复此版本', 'Restore this version')}</button></Modal>}
  </section>;
}
