"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import { Download, RefreshCw, Sparkles, Upload } from 'lucide-react';
import type { StudioProfile } from '@/lib/native-studio';
import { PET_ROWS, PET_DURATIONS, type PetCandidate, type PetIndex } from '@/lib/native-pet';
import { useWorkbench, errorText } from './NativeWorkbenchProvider';
import { Modal } from './WorkbenchShell';
const labels=['休息','向右走','向左走','招手','跳跃','失落','等你回应','工作中','仔细查看'];
export function PetManager({close,changed}:{close:()=>void;changed:()=>void}){
  const {request,t}=useWorkbench();const [index,setIndex]=useState<PetIndex>({packages:[],jobs:[],selected:{id:null},invalid:[]});
  const [models,setModels]=useState<StudioProfile[]>([]),[profile,setProfile]=useState(''),[name,setName]=useState(''),[prompt,setPrompt]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[directory,setDirectory]=useState('');
  const [preview,setPreview]=useState<PetCandidate|null>(null),[row,setRow]=useState(0),[frame,setFrame]=useState(0);const submission=useRef<{body:string;key:string}|null>(null);
  const [retryJob,setRetryJob]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const result=await request<PetIndex>('studio/pet/list');setIndex(result);},[request]);
  useEffect(()=>{void Promise.all([refresh(),request<{profiles:StudioProfile[]}>('studio/models').then(v=>{setModels(v.profiles.filter(p=>p.kind==='image'&&(p.inputCapabilities?.maxReferences??0)>0));})]).catch(e=>setError(errorText(e)));},[refresh,request]);
  const pending=index.jobs.some(j=>j.status==='running');
  useEffect(()=>{if(!pending)return;let running=false;const id=setInterval(()=>{if(!running&&!document.hidden){running=true;void refresh().catch(e=>setError(errorText(e))).finally(()=>{running=false;});}},2000);return()=>clearInterval(id);},[pending,refresh]);
  useEffect(()=>{if(!preview)return;const start=Date.now(),times=PET_DURATIONS[row];const tick=()=>{if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches){setFrame(0);return;}let time=(Date.now()-start)%times.reduce((a,b)=>a+b,0),n=0;while(n<times.length-1&&time>=times[n])time-=times[n++];setFrame(n);};const timer=setInterval(tick,60);return()=>clearInterval(timer);},[preview,row]);
  const act=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await action();await refresh();changed();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const create=()=>act(async()=>{const payload={name:name||t('新伙伴','New companion'),prompt,profileId:profile||models[0]?.id};const body=JSON.stringify(payload);if(submission.current?.body!==body)submission.current={body,key:crypto.randomUUID()};await request('studio/pet/create',{...payload,idempotencyKey:submission.current.key});submission.current=null;setPrompt('');setNotice(t('已开始创建，可关闭此窗口，进度会保留。','Creation started. You can close this window; progress is saved.'));});
  return <Modal title={t('宠物伙伴','Companions')} close={close} busy={busy}><div className="pet-manager">
    <p className="ns-hint">{t('跟着真实任务一起工作。创建后先查看动作，再决定是否选用。','A companion that follows your real tasks. Preview its poses before choosing it.')}</p>
    <div className="pet-library"><button className={`pet-choice ${!index.selected.id?'is-selected':''}`} disabled={busy} onClick={()=>void act(()=>request('studio/pet/select',{id:null}))}>{t('内置伙伴','Built-in companion')}</button>{index.packages.map(p=><button key={p.id} className={`pet-choice ${index.selected.id===p.id?'is-selected':''}`} onClick={()=>void act(async()=>{setPreview(await request<PetCandidate>('studio/pet/read',{id:p.id}));setRow(0);})}>{p.manifest.displayName}</button>)}</div>
    {preview&&<section className="pet-preview"><div className="pet-preview-stage"><div style={{width:192,height:208,backgroundImage:`url("${preview.url}")`,backgroundPosition:`-${frame*192}px -${row*208}px`}} /></div><label>{t('预览动作','Preview pose')}<select value={row} onChange={e=>{setRow(Number(e.target.value));setFrame(0);}}>{PET_ROWS.map((state,i)=><option key={state} value={i}>{t(labels[i],state)}</option>)}</select></label>{preview.qa.warnings.length>0&&<p className="ns-hint">{preview.qa.warnings.slice(0,3).join('；')}</p>}<p className="ns-hint">{t('结构检查不代替视觉判断：请确认角色一致、透明边缘和动作自然。','Structural checks do not replace visual review. Check identity, transparency and movement.')}</p><div className="ns-dialog-actions"><button className="nw-button" disabled={busy} onClick={()=>void act(async()=>{const result=await request<{exportedTo:string}>('studio/pet/export',{id:preview.id});setNotice(`${t('已导出到','Exported to')} ${result.exportedTo}`);})}><Download size={14}/>{t('导出','Export')}</button><button className="nw-button" disabled={busy||!models.length} onClick={()=>void act(()=>request('studio/pet/repair',{id:preview.id,row:PET_ROWS[row],profileId:profile||models[0]?.id,idempotencyKey:crypto.randomUUID()}))}><RefreshCw size={14}/>{t('重新生成此动作','Regenerate this pose')}</button><button className="nw-button nw-primary" disabled={busy||!preview.qa.passed} onClick={()=>void act(()=>request('studio/pet/select',{id:preview.id,reviewed:true}))}>{t('已查看，选用它','Reviewed, use this companion')}</button></div></section>}
    {index.jobs.slice(0,10).map(job=><div key={job.id} className="pet-job"><span>{job.input.name} · {job.status==='succeeded'?t('待选用','Ready to choose'):`${job.pipeline?.completedRows??0}/9 ${t('种动作','poses')}`}</span>{job.error&&<p role="status">{job.error}</p>}{job.status==='running'&&<button disabled={busy} className="nw-button" onClick={()=>void act(()=>request(job.active?'studio/pet/cancel':'studio/pet/resume',{id:job.id}))}>{job.active?t('暂停','Pause'):t('继续原任务','Continue existing task')}</button>}{job.phase==='needs-attention'&&job.pipeline?.phase?.startsWith('generating-')&&<button className="nw-button" disabled={busy} onClick={()=>retryJob===job.id?void act(async()=>{await request('studio/pet/retry',{id:job.id,stage:job.pipeline?.phase?.slice(11),confirmRegenerate:true});setRetryJob(null);}):setRetryJob(job.id)}>{retryJob===job.id?t('确认新建一次生成，可能再次计费','Confirm a new generation; additional charges may apply'):t('重新生成此动作','Regenerate this pose')}</button>}</div>)}
    <details className="pet-create"><summary><Sparkles size={15}/>{t('创建新伙伴','Create a companion')}</summary><label>{t('名字','Name')}<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><label>{t('描述外观和风格','Describe its appearance and style')}<textarea rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={4000}/></label><label>{t('图片模型','Image model')}<select value={profile||models[0]?.id||''} onChange={e=>setProfile(e.target.value)}>{!models.length&&<option value="">{t('请先在创作台添加支持参考图的模型','Add a reference-capable image model in Studio first')}</option>}{models.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="ns-hint">{t('完整创建最多生成 10 张图片：1 张身份参考与 9 种动作。使用你自己的模型账户；仅在你点击创建后开始。','A full hatch makes up to 10 images: one identity reference and nine poses, billed to your provider. Generation starts only when you choose Create.')}</p><button className="nw-button nw-primary" disabled={busy||!prompt.trim()||!models.length} onClick={()=>void create()}>{t('创建伙伴','Create companion')}</button></details>
    <details className="pet-create"><summary><Upload size={15}/>{t('导入已有宠物包','Import a pet package')}</summary><label>{t('宠物包文件夹','Pet package folder')}<input value={directory} onChange={e=>setDirectory(e.target.value)} placeholder={t('D:\\pets\\my-pet', 'D:\\pets\\my-pet')}/></label><p className="ns-hint">{t('支持 pet.json / manifest.json 与 PNG、WebP 图集，原文件保留。','Supports pet.json / manifest.json with PNG or WebP atlases. Original files are preserved.')}</p><button className="nw-button" disabled={busy||!directory.trim()} onClick={()=>void act(()=>request('studio/pet/import',{directory}))}>{t('导入','Import')}</button></details>
    {error&&<p role="alert" className="nw-inline-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  </div></Modal>;
}
