"use client";
import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import type { StudioProfile } from '@/lib/native-studio';
import { Modal } from './WorkbenchShell';
import { errorText, useWorkbench } from './NativeWorkbenchProvider';
import { StudioWorkflow } from './StudioWorkflow';

const blank = (kind: 'image' | 'video'): StudioProfile => ({ id: '', name: '', kind, protocol: 'openai', baseUrl: 'https://api.openai.com/v1', model: kind === 'image' ? 'gpt-image-2' : 'sora-2', authHeader: 'Authorization', authPrefix: 'Bearer', agentEnabled: false, extra: {}, custom: {} });
export function StudioConnections({ profiles, kind, close, saved }: { profiles: StudioProfile[]; kind: 'image' | 'video'; close: () => void; saved: (profile?: StudioProfile) => Promise<void> }) {
  const { request, t } = useWorkbench();
  const [form, setForm] = useState<StudioProfile>(() => profiles.find(p => p.kind === kind) ?? blank(kind));
  const [key, setKey] = useState(''), [clearKey, setClearKey] = useState(false), [extra, setExtra] = useState(() => JSON.stringify(form.extra, null, 2)), [custom, setCustom] = useState(() => JSON.stringify(form.custom, null, 2));
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [removing, setRemoving] = useState(false);
  let mapping: Record<string, unknown> = {}; try { mapping = JSON.parse(custom); } catch { /* Keep a partially edited JSON draft. */ }
  const configureInputs = (patch: Record<string, unknown>) => {
    try { const next = { ...JSON.parse(custom), ...patch }; setCustom(JSON.stringify(next, null, 2)); setNotice(''); }
    catch { setError(t('请先修正高级设置中的 JSON', 'Fix the JSON in advanced settings first')); }
  };
  const change = (patch: Partial<StudioProfile>) => { setForm(v => ({ ...v, ...patch })); setNotice(''); setRemoving(false); };
  const choose = (p: StudioProfile) => { setForm(p); setKey(''); setClearKey(false); setExtra(JSON.stringify(p.extra, null, 2)); setCustom(JSON.stringify(p.custom, null, 2)); setError(''); setNotice(''); setRemoving(false); };
  const save = async () => {
    if (busy) return; setBusy(true); setError('');
    try {
      const profile = await request<StudioProfile>('studio/model/save', { ...form, id: form.id || undefined, apiKey: clearKey ? '' : key || undefined, extra: JSON.parse(extra), custom: JSON.parse(custom) });
      setKey(''); await saved(profile); close();
    } catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  };
  return <Modal title={t('创作模型', 'Creative models')} close={close} busy={busy}>
    <form className="ns-connection" onSubmit={event => { event.preventDefault(); void save(); }}>
      <fieldset disabled={busy}>
        <div className="ns-connection-select"><select aria-label={t('已保存的连接', 'Saved connections')} value={form.id} onChange={e => choose(profiles.find(p => p.id === e.target.value) ?? blank(kind))}><option value="">{t('新连接', 'New connection')}</option>{profiles.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button type="button" className="nw-button" onClick={() => choose(blank(kind))}><Plus size={15} />{t('添加', 'Add')}</button></div>
        <div className="ns-form-grid"><label>{t('连接名称', 'Name')}<input required maxLength={100} value={form.name} onChange={e => change({ name: e.target.value })} placeholder={t('例如：我的图片模型', 'e.g. My image model')} /></label><label>{t('媒体类型', 'Media type')}<select aria-label={t('媒体类型', 'Media type')} value={form.kind} onChange={e => change({ kind: e.target.value as StudioProfile['kind'] })}><option value="image">{t('图片', 'Image')}</option><option value="video">{t('视频', 'Video')}</option></select></label></div>
        <label>{t('接口协议', 'Protocol')}<select value={form.protocol} onChange={e => { const protocol = e.target.value as StudioProfile['protocol']; const urls = { openai: 'https://api.openai.com/v1', fal: 'https://queue.fal.run', gemini: 'https://generativelanguage.googleapis.com/v1beta', runway: 'https://api.dev.runwayml.com/v1', replicate: 'https://api.replicate.com/v1', comfyui: 'http://127.0.0.1:8188', json: form.baseUrl }; change({ protocol, baseUrl: urls[protocol], authHeader: protocol === 'gemini' ? 'x-goog-api-key' : 'Authorization', authPrefix: protocol === 'gemini' ? '' : protocol === 'fal' ? 'Key' : 'Bearer', ...(['runway','replicate'].includes(protocol) ? { kind: 'video' as const } : {}) }); setCustom('{}'); }}><option value="openai">{t('OpenAI 兼容', 'OpenAI compatible')}</option><option value="fal">{t('fal 队列', 'fal queue')}</option><option value="gemini">{t('Gemini / Veo', 'Gemini / Veo')}</option><option value="runway">{t('Runway', 'Runway')}</option><option value="replicate">{t('Replicate', 'Replicate')}</option><option value="comfyui">{t('ComfyUI', 'ComfyUI')}</option><option value="json">{t('自定义 JSON', 'Custom JSON')}</option></select></label>
        <label>{t('接口地址', 'API base URL')}<input required type="url" value={form.baseUrl} onChange={e => change({ baseUrl: e.target.value })} spellCheck={false} /></label>
        <label>{t('模型名称或端点', 'Model or endpoint')}<input required value={form.model} onChange={e => change({ model: e.target.value })} spellCheck={false} /></label>
        <label>{t('API 密钥', 'API key')}<input type="password" autoComplete="off" value={key} onChange={e => { setKey(e.target.value); setClearKey(false); }} placeholder={form.keyConfigured ? t('已配置，留空保留', 'Configured; leave blank to keep') : t('本地无鉴权服务可留空', 'Optional for a local service without authentication')} /></label>
        {form.keyConfigured && <label className="ns-check"><input type="checkbox" checked={clearKey} onChange={e => setClearKey(e.target.checked)} />{t('清除已保存的密钥', 'Clear saved key')}</label>}
        <p className="ns-hint">{t('桌面版使用系统加密保存密钥；浏览器调试中的密钥仅本次服务运行有效。模型服务的用量由你自己的账户承担。', 'Desktop credentials use system encryption; browser development credentials last for this service session. Usage is billed to your own provider account.')}</p>
        <label className="ns-check"><input type="checkbox" checked={form.agentEnabled} onChange={e => change({ agentEnabled: e.target.checked })} />{t('允许 Agent 使用此模型创作', 'Allow the Agent to create with this model')}</label>
        {form.protocol === 'fal' && (form.kind === 'video' ? <label>{t('视频图像输入', 'Video image inputs')}<select aria-label={t('视频图像输入', 'Video image inputs')} value={mapping.firstFrameField === undefined && mapping.lastFrameField === undefined ? 'auto' : mapping.lastFrameField ? mapping.firstFrameField === 'image_url' ? 'image-end' : 'start-end' : mapping.firstFrameField === '' ? 'none' : 'first'} onChange={e => configureInputs(e.target.value === 'auto' ? { firstFrameField: undefined, lastFrameField: undefined } : e.target.value === 'none' ? { firstFrameField: '', lastFrameField: '' } : e.target.value === 'first' ? { firstFrameField: 'image_url', lastFrameField: '' } : { firstFrameField: e.target.value === 'image-end' ? 'image_url' : 'start_image_url', lastFrameField: 'end_image_url' })}>
          <option value="auto">{t('按模型端点识别', 'Detect from model endpoint')}</option><option value="first">{t('仅首帧', 'First frame only')}{' · image_url'}</option><option value="start-end">{t('首尾帧', 'First and last frames')}{' · start_image_url / end_image_url'}</option><option value="image-end">{t('首尾帧', 'First and last frames')}{' · image_url / end_image_url'}</option><option value="none">{t('不使用图像输入', 'No image input')}</option>
        </select><span className="ns-hint">{t('以服务商接口文档为准；保存后创作台会显示可用帧位。', 'Match your provider documentation. Available frame slots appear after saving.')}</span></label>
        : <label>{t('图片参考输入', 'Image references')}<select aria-label={t('图片参考输入', 'Image references')} value={String(mapping.referenceMode ?? 'single')} onChange={e => configureInputs({ referenceMode: e.target.value, referenceField: undefined })}><option value="single">{t('单张参考图', 'One reference')}{' · image_url'}</option><option value="multiple">{t('多张参考图', 'Multiple references')}{' · image_urls'}</option><option value="none">{t('不支持参考图', 'No reference images')}</option></select></label>)}
        {form.kind === 'video' && form.protocol === 'openai' && <p className="ns-hint">{t('此协议使用 input_reference 传首帧。尾帧请使用支持首尾帧的 fal 或自定义 JSON 接口。', 'This protocol sends a first frame as input_reference. Use a compatible fal or custom JSON endpoint for a last frame.')}</p>}
        {form.protocol === 'replicate' && <div className="ns-form-grid"><label>{t('首帧字段（按模型文档填写）', 'First-frame field from model schema')}<input value={String(mapping.imageInputField ?? '')} onChange={e => configureInputs({ imageInputField: e.target.value })} placeholder={t('image', 'image')} /></label><label>{t('尾帧字段（可留空）', 'Last-frame field, optional')}<input value={String(mapping.lastFrameField ?? '')} onChange={e => configureInputs({ lastFrameField: e.target.value })} placeholder={t('end_image', 'end_image')} /></label></div>}
        {form.protocol === 'runway' && <p className="ns-hint">{t('Gen4 Turbo 需要首帧；Veo 3.1 支持首尾帧。画幅会按模型协议转换，取消请求带 API 版本。', 'Gen4 Turbo requires a first frame; Veo 3.1 supports both frames. Ratios and cancellation follow the model API.')}</p>}
        {form.protocol === 'comfyui' && <StudioWorkflow key={`${form.id}:${form.kind}`} custom={custom} kind={form.kind} change={setCustom} />}
        <details className="ns-advanced"><summary>{t('高级接口设置', 'Advanced API settings')}</summary>
          <div className="ns-form-grid"><label>{t('鉴权请求头', 'Authentication header')}<input value={form.authHeader} onChange={e => change({ authHeader: e.target.value })} /></label><label>{t('密钥前缀', 'Key prefix')}<input value={form.authPrefix} onChange={e => change({ authPrefix: e.target.value })} /></label></div>
          <label>{t('附加请求参数（JSON 对象）', 'Extra request parameters (JSON object)')}<textarea rows={5} value={extra} onChange={e => setExtra(e.target.value)} spellCheck={false} /></label>
          {['gemini','runway','replicate','comfyui'].includes(form.protocol) && <label>{t('协议配置（JSON）', 'Protocol configuration (JSON)')}<textarea rows={10} value={custom} onChange={e => setCustom(e.target.value)} spellCheck={false} placeholder={form.protocol === 'comfyui' ? '{"workflow": {}, "bindings": {"prompt": {"node": "6", "input": "text"}}, "outputNode": "9"}' : '{}'} /></label>}
          {form.protocol === 'json' && <><label>{t('请求与结果映射（JSON）', 'Request and result mapping (JSON)')}<textarea rows={10} value={custom} onChange={e => setCustom(e.target.value)} spellCheck={false} /></label><p className="ns-hint">{t('支持 createPath、requestTemplate、idPath、statusPathTemplate、statusPath、outputPath、successValues、failureValues。模板变量：', 'Fields: createPath, requestTemplate, idPath, statusPathTemplate, statusPath, outputPath, successValues, failureValues. Variables: ')}<code>{'{{prompt}} {{model}} {{size}} {{seconds}} {{count}} {{images}} {{first_frame}} {{last_frame}}'}</code></p><button type="button" className="nw-button" onClick={() => setCustom(JSON.stringify({ createPath: 'generate', requestTemplate: { model: '{{model}}', prompt: '{{prompt}}', images: '{{images}}', first_frame: '{{first_frame}}', last_frame: '{{last_frame}}' }, idPath: 'id', statusPathTemplate: 'jobs/{{id}}', statusPath: 'status', outputPath: 'outputs', successValues: ['completed'], failureValues: ['failed', 'cancelled'] }, null, 2))}>{t('填入异步接口示例', 'Insert an asynchronous example')}</button></>}
        </details>
      </fieldset>
      {error && <p role="alert" className="nw-inline-error">{error}</p>}{notice && <p role="status">{notice}</p>}
      <div className="ns-dialog-actions">{form.id && <button type="button" className="nw-icon" disabled={busy} aria-label={t('删除模型连接', 'Delete model connection')} onClick={() => setRemoving(v => !v)}><Trash2 size={16} /></button>}{removing && <button type="button" className="nw-button" disabled={busy} onClick={async () => { setBusy(true); try { await request('studio/model/remove', { id: form.id }); await saved(); choose(blank(kind)); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}>{t('确认删除连接', 'Confirm deletion')}</button>}<span />{form.id && <button type="button" className="nw-button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { const result = await request<{ reachable: boolean | null; issues?: string[] }>('studio/model/test', { id: form.id }); setNotice(result.issues?.length ? result.issues.join('；') : result.reachable ? t('已保存的接口连接正常', 'Saved API connection succeeded') : t('配置可用；此协议将在首次创作时验证服务响应', 'Configuration is valid; this protocol is verified on its first generation')); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}>{t('测试已保存配置', 'Test saved settings')}</button>}<button className="nw-button nw-primary" disabled={busy}>{busy ? t('正在保存…', 'Saving…') : t('保存连接', 'Save connection')}</button></div>
    </form>
  </Modal>;
}
