'use client';
import { useCallback, useEffect, useState } from 'react';
import { ArrowUpRight, Files, GitBranch, Lock, Plus, RefreshCw, ShieldCheck, Trash2, Unlock } from 'lucide-react';
import { useRouter } from 'next/navigation';
import type { Workspace } from '@/lib/native-workbench-state';
import { errorText, useWorkbench } from './NativeWorkbenchProvider';
import { Modal } from './WorkbenchShell';
import { WorktreeReview } from './WorktreeReview';
import './worktree-manager.css';
type Worktree = { path: string; branch: string | null; head: string | null; main: boolean; managed: boolean; locked: boolean; lockReason?: string; prunable: boolean };
type Snapshot = { snapshotId: string; head: string; changedFiles: number; untrackedFiles: number; bytes: number; expiresAt: string; state?: string; branch?: string; result?: { status: string; workspace: Workspace | null; error?: string } };
export function WorktreeManager({ workspaceId }: { workspaceId: string }) {
  const { request, t, refresh, workspaces, setWorkspaceId, connection } = useWorkbench(); const router = useRouter();
  const [available, setAvailable] = useState(true), [entries, setEntries] = useState<Worktree[]>([]), [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [creating, setCreating] = useState(false), [branch, setBranch] = useState(''), [baseRef, setBaseRef] = useState('HEAD'), [copyChanges, setCopyChanges] = useState(false), [snapshot, setSnapshot] = useState<Snapshot>();
  const [removing, setRemoving] = useState<Worktree>(), [discarding, setDiscarding] = useState<Snapshot>(), [reviewing, setReviewing] = useState(false);
  const load = useCallback(async () => {
    const result = await request<{ available: boolean; worktrees?: Worktree[] }>('workspace/worktree/list', { workspaceId }); setAvailable(result.available); setEntries(result.worktrees || []);
    if (result.available) { const list = await request<{ snapshots: Snapshot[] }>('worktree/snapshot/list', { workspaceId }); setSnapshots(list.snapshots); }
  }, [request, workspaceId]);
  useEffect(() => { if (connection === 'connected') { setError(''); void load().catch(e => setError(errorText(e))); } }, [load, connection]);
  useEffect(() => { setSnapshot(undefined); }, [copyChanges, workspaceId]);
  const action = async (work: () => Promise<void>) => { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const open = async (workspace: Workspace) => { await refresh(); setWorkspaceId(workspace.id); router.push(`/workbench/project/${encodeURIComponent(workspace.id)}`); };
  return <section className="nw-worktree-manager" aria-label={t('独立工作目录', 'Worktrees')}>
    <div className="nw-page-heading"><div><h2><GitBranch size={20} />{t('独立工作目录', 'Worktrees')}</h2><p>{t('为并行任务保留独立文件与分支，也可以带上当前未提交的改动。', 'Keep separate files and branches for parallel tasks, with an option to copy current uncommitted changes.')}</p></div><div className="nw-worktree-actions"><button className="nw-icon" aria-label={t('刷新工作目录', 'Refresh worktrees')} disabled={busy} onClick={() => void action(load)}><RefreshCw size={15} /></button><button className="nw-button" disabled={busy || !available} onClick={() => setReviewing(true)}><ShieldCheck size={15} />{t('交付预检', 'Delivery review')}</button><button className="nw-button" disabled={busy || !available} onClick={() => { setCreating(true); setBranch(''); setBaseRef('HEAD'); setCopyChanges(false); setSnapshot(undefined); setError(''); }}><Plus size={15} />{t('创建', 'Create')}</button></div></div>
    {error && <p className="nw-inline-error" role="alert">{error}</p>}{notice && <p className="nw-help" role="status">{notice}</p>}
    {!available && <p className="nw-help">{t('这个项目尚未使用 Git。', 'This project does not use Git yet.')}</p>}
    {entries.map(entry => { const workspace = workspaces.find(w => w.cwd?.replaceAll('\\', '/').toLowerCase() === entry.path.replaceAll('\\', '/').toLowerCase()); return <article className="nw-worktree-entry" key={entry.path}><GitBranch size={18} /><div><strong>{entry.branch?.replace(/^refs\/heads\//, '') || entry.head?.slice(0, 10) || t('独立目录', 'Worktree')}</strong><small>{entry.path}</small><span>{entry.main ? t('主工作目录', 'Main worktree') : entry.locked ? t('已锁定并保留', 'Locked and retained') : entry.managed ? t('Knorvia 管理', 'Managed by Knorvia') : t('外部工作目录', 'External worktree')}</span>{entry.lockReason && <small>{entry.lockReason}</small>}</div><div className="nw-worktree-actions">{workspace && <button className="nw-icon" aria-label={t('打开项目', 'Open project')} onClick={() => void open(workspace)}><ArrowUpRight size={16} /></button>}{!entry.main && <button className="nw-icon" disabled={busy} aria-label={entry.locked ? t('解除锁定', 'Unlock') : t('锁定并保留', 'Lock and retain')} onClick={() => void action(async () => { await request(entry.locked ? 'workspace/worktree/unlock' : 'workspace/worktree/lock', { workspaceId, path: entry.path, ...(entry.locked ? {} : { reason: t('由 Knorvia 保留', 'Retained by Knorvia') }) }); })}>{entry.locked ? <Unlock size={15} /> : <Lock size={15} />}</button>}{entry.managed && !entry.main && <button className="nw-icon" disabled={busy || entry.locked} aria-label={t('移除工作目录', 'Remove worktree')} onClick={() => setRemoving(entry)}><Trash2 size={15} /></button>}</div></article>; })}
    {snapshots.length > 0 && <details className="nw-worktree-snapshots"><summary><Files size={15} />{t('保留的改动快照', 'Retained change snapshots')} ({snapshots.length})</summary>{snapshots.map(item => <div key={item.snapshotId}><span>{item.branch || item.head.slice(0, 10)}<small>{item.changedFiles} {t('个改动', 'changes')} · {(item.bytes / 1024).toFixed(1)} {t('KB', 'KB')} · {item.state === 'needs-recovery' || item.state === 'creating' ? t('需要检查', 'Needs inspection') : item.state === 'completed' ? t('已复制', 'Copied') : t('已准备', 'Prepared')}</small>{item.result?.error && <small>{item.result.error}</small>}</span>{item.result?.workspace && <button className="nw-icon" aria-label={t('检查工作目录', 'Inspect worktree')} onClick={() => void open(item.result!.workspace!)}><ArrowUpRight size={15} /></button>}<button className="nw-icon" disabled={busy || !['completed', 'inspected'].includes(item.state || '')} aria-label={t('删除快照', 'Discard snapshot')} onClick={() => setDiscarding(item)}><Trash2 size={14} /></button></div>)}</details>}
    {creating && <Modal title={t('创建独立工作目录', 'Create worktree')} close={() => setCreating(false)} busy={busy}><div className="nw-worktree-form"><label className="nw-field">{t('新分支名称', 'New branch name')}<input autoFocus value={branch} disabled={busy} onChange={e => setBranch(e.target.value)} placeholder={t('feature/my-task', 'feature/my-task')} /></label><label className="nw-worktree-check"><input type="checkbox" disabled={busy} checked={copyChanges} onChange={e => setCopyChanges(e.target.checked)} />{t('带上当前未提交的改动', 'Copy current uncommitted changes')}</label>{copyChanges ? <><p className="nw-help">{t('保留暂存区、未暂存改动和未跟踪文件。源目录与原暂存区保持原样，忽略文件不会复制。', 'Preserve staged changes, unstaged edits, and untracked files. The source and its index stay unchanged; ignored files are excluded.')}</p><button className="nw-button" disabled={busy} onClick={() => void action(async () => setSnapshot(await request<Snapshot>('worktree/snapshot/inspect', { workspaceId })))}><Files size={14} />{t('检查并准备快照', 'Inspect and prepare snapshot')}</button>{snapshot && <p className="nw-help">{snapshot.changedFiles} {t('个改动，其中新增文件', 'changes, including new files')}: {snapshot.untrackedFiles} · {(snapshot.bytes / 1024).toFixed(1)} {t('KB', 'KB')}</p>}</> : <label className="nw-field">{t('起始版本', 'Starting revision')}<input value={baseRef} disabled={busy} onChange={e => setBaseRef(e.target.value)} /></label>}{error && <p className="nw-inline-error" role="alert">{error}</p>}<button className="nw-button nw-button-primary" disabled={busy || !branch.trim() || (copyChanges && !snapshot)} onClick={() => void action(async () => { if (copyChanges) { const result = await request<{ status: string; workspace: Workspace | null; error?: string }>('worktree/snapshot/create', { workspaceId, snapshotId: snapshot!.snapshotId, branch: branch.trim() }); if (result.status !== 'completed' || !result.workspace) { setSnapshot(undefined); throw new Error(result.error || t('已保留快照，请检查独立工作目录。', 'Snapshot retained. Inspect the new worktree.')); } setCreating(false); await open(result.workspace); } else { const workspace = await request<Workspace>('workspace/worktree/create', { workspaceId, branch: branch.trim(), baseRef: baseRef.trim() || 'HEAD' }); setCreating(false); await open(workspace); } })}><GitBranch size={15} />{t('创建工作目录', 'Create worktree')}</button></div></Modal>}
    {reviewing && <WorktreeReview workspaceId={workspaceId} close={() => setReviewing(false)} />}
    {removing && <Modal title={t('移除工作目录', 'Remove worktree')} close={() => setRemoving(undefined)} busy={busy}><p>{t('仅移除干净、未锁定的 Knorvia 工作目录。任何未提交或忽略文件都会阻止操作，分支与对话历史会保留。', 'Only a clean, unlocked Knorvia worktree can be removed. Uncommitted or ignored files block removal. Branches and conversation history are retained.')}</p><p className="nw-help">{removing.path}</p>{error && <p className="nw-inline-error" role="alert">{error}</p>}<div className="nw-dialog-actions"><button className="nw-button" disabled={busy} onClick={() => setRemoving(undefined)}>{t('取消', 'Cancel')}</button><button className="nw-button" disabled={busy} onClick={() => void action(async () => { await request('workspace/worktree/remove', { workspaceId, path: removing.path }); setRemoving(undefined); await refresh(); setNotice(t('工作目录已移除，分支与对话历史已保留。', 'Worktree removed. Its branch and conversation history are retained.')); })}>{t('检查并移除', 'Check and remove')}</button></div></Modal>}
    {discarding && <Modal title={t('删除改动快照', 'Discard change snapshot')} close={() => setDiscarding(undefined)} busy={busy}><p>{t('只删除这份备份，源目录和已创建的工作目录会保留。', 'Delete only this backup. The source and created worktree will remain.')}</p><button className="nw-button" disabled={busy} onClick={() => void action(async () => { await request('worktree/snapshot/discard', { workspaceId, snapshotId: discarding.snapshotId }); setDiscarding(undefined); })}>{t('删除快照', 'Discard snapshot')}</button></Modal>}
  </section>;
}
