# -*- coding: utf-8 -*-
"""Remove generated build artifacts from the Knorvia source tree.

Usage:
    python scripts/clean_artifacts.py            # dry run: show what would go
    python scripts/clean_artifacts.py --yes      # actually delete

Everything listed here is already covered by .gitignore. Build outputs are
regenerated by the normal build/packaging flow, so deleting them is always
safe.
"""

import argparse
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]

# Whole directories that are pure build output / local runtime copies.
DIRS = [
    "dist",  # packaged wheels + portable bundles
    # Final deliveries under release/ are retained separately: latest verified
    # version, one rollback and independent skill packages. Never wipe the root.
    "build",  # setuptools bdist output
    "knorvia_web",  # standalone web package (from web/.next)
    # desktop-data is the actual development workspace, including user content.
    # It must never be treated as a regenerable build artifact.
    "knorvia.egg-info",
    "web/.next",
    "web/.next-knorvia",
    "web/test-results",
    "web/playwright-report",
    ".pytest_cache",
    ".ruff_cache",
]

# Loose files from ad-hoc analysis / tooling runs.
FILES = [
    "eslint-report.json",
]


def size_of(p: Path) -> int:
    if p.is_file():
        return p.stat().st_size
    total = 0
    for child in p.rglob("*"):
        try:
            if child.is_file():
                total += child.stat().st_size
        except OSError:
            pass
    return total


def fmt(n: int) -> str:
    n = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return "%.1f %s" % (n, unit)
        n /= 1024.0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--yes", action="store_true", help="actually delete")
    args = ap.parse_args()

    targets = []
    for name in DIRS:
        p = ROOT / name
        if p.exists():
            targets.append(p)
    for name in FILES:
        p = ROOT / name
        if p.exists():
            targets.append(p)

    if not targets:
        print("Nothing to clean - tree is already free of build artifacts.")
        return 0

    total = 0
    print("Build artifacts found:")
    for p in sorted(targets):
        s = size_of(p)
        total += s
        print("  %-40s %10s" % (p.relative_to(ROOT).as_posix(), fmt(s)))

    if not args.yes:
        print("\nDry run only. Re-run with --yes to delete.")
        return 0

    for p in targets:
        if p.is_dir():
            shutil.rmtree(p, ignore_errors=False)
        else:
            p.unlink()
    print("\nDeleted %d targets (%s freed)." % (len(targets), fmt(total)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
